### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)   File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 142, in _get_module_details     return _get_module_details(pkg_main_name, error)   File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details     __import__(pkg_name)   File "C:\Users\Blood\Desktop\xuexi\xuexi\__init__.py", line 26, in <module>     cfg.read(path/'config-default.ini', encoding='utf-8')   File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 693, in read     for filename in filenames: TypeError: 'WindowsPath' object is not iterable

### ISSUE THREAD

**Issue by IConquer96** [kessil/AutoXue#106]
按照readme配置了custom文件，但出现这个问题，求大神告知如何解决？

Traceback (most recent call last):
  File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Blood\Desktop\xuexi\xuexi\__init__.py", line 26, in <module>
    cfg.read(path/'config-default.ini', encoding='utf-8')
  File "C:\Users\Blood\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'WindowsPath' object is not iterable

**Comment by kessil** [comment]
是不是文件名不对？

**Comment by IConquer96** [comment]
文件名都没有修改过，重新下了最新的，没修改也这样

**Comment by kessil** [comment]
你的os和python版本？

**Comment by IConquer96** [comment]
win10 3.6.0

**Comment by kessil** [comment]
尝试一下将./xuexi/__init__.py第26、27行的path/'config-xxx.ini'用str()包起来
改成这样子
```python
cfg.read(str(path/'config-default.ini'), encoding='utf-8')
cfg.read(str(path/'config-custom.ini'), encoding='utf-8')
```
