### ISSUE TITLE
新版本错误

### ISSUE THREAD

**Issue by tb4554565** [kessil/AutoXue#141]
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side e
rror occurred while processing the command. Original error: Could not proxy. Pro
xy error: Could not proxy command to remote server. Original error: 404 - undefi
ned

**Comment by kessil** [comment]
信息太少没办法提供参考抱歉

**Comment by tb4554565** [comment]
大佬，网上查了还是没解决这个问题，麻烦指点一二
C:\Users\Administrator\Desktop\AutoXue-master
Appium.exe                    9440 Console                    1    661,808 K
Appium.exe                   10340 Console                    1     56,540 K
Appium.exe                   10312 Console                    1    170,368 K
Appium is running
Nox.exe                       8276 Console                    1     28,856 K
Nox is running
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__main__.py", line 17, in <module>
    app = App()
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 120, in __init__
    self.view_score()
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 137, in view_score
    self.safe_back('score -> home')
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 97, in safe_back
    self.driver.keyevent(4)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\extensions\keyboard.py", line 70, in keyevent
    self.execute(Command.KEY_EVENT, data)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to rem
ote server. Original error: 404 - undefined

xuexi successfully!
请按任意键继续. . .

**Comment by tb4554565** [comment]
大佬，网上查了还是没解决这个问题，麻烦指点一二
C:\Users\Administrator\Desktop\AutoXue-master
Appium.exe                    9440 Console                    1    661,808 K
Appium.exe                   10340 Console                    1     56,540 K
Appium.exe                   10312 Console                    1    170,368 K
Appium is running
Nox.exe                       8276 Console                    1     28,856 K
Nox is running
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__main__.py", line 17, in <module>
    app = App()
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 120, in __init__
    self.view_score()
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 137, in view_score
    self.safe_back('score -> home')
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 97, in safe_back
    self.driver.keyevent(4)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\extensions\keyboard.py", line 70, in keyevent
    self.execute(Command.KEY_EVENT, data)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\Administrator\Desktop\AutoXue-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to rem
ote server. Original error: 404 - undefined

xuexi successfully!
请按任意键继续. . .
