### ISSUE TITLE
这个程序怎样带参数运行？

### ISSUE THREAD

**Issue by hydjq** [kessil/AutoXue#152]
main里有-u和-p的参数，想问一下这个是否可以带参数运行那？运行参数的格式是怎样的？比如 start-u用户名-ppassword 是这样吗？我试了几次都无法运行，想请教一下正确的运行格式是怎样的？start-u“用户名”-p“password” 我都试了，都不行！望大神指点！！万分感谢！万分感谢！万分感谢！

**Comment by kessil** [comment]
> 
> 
> main里有-u和-p的参数，想问一下这个是否可以带参数运行那？运行参数的格式是怎样的？比如 start-u用户名-ppassword 是这样吗？我试了几次都无法运行，想请教一下正确的运行格式是怎样的？start-u“用户名”-p“password” 我都试了，都不行！望大神指点！！万分感谢！万分感谢！万分感谢！

针对没有预先登录的情况，可是使用如下调用自动登录账号并开始学习
`(venv)$:python -m xuexi -u your_username -p your_password`

**Comment by hydjq** [comment]
感谢大神这么快就给了回复，按照你的思路我将start里的这个语句进行了修改：venv\scripts\python -m xuexi -u 用户名 -p 密码 ，运行后可以直接进行自动登录并进入界面，但进入界面后直接退出，并未进行相关动作！错误代码如下：C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev
Appium.exe                   11092 Console                    1    166,768 K
Appium.exe                   10308 Console                    1     39,756 K
Appium.exe                   11260 Console                    1    197,012 K
Nox.exe                      11636 Console                    1     28,080 K
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__main__.py", line 22, in <module>
    app = App(args.username, args.password)
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__init__.py", line 145, in __init__
    self.login_or_not()
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__init__.py", line 181, in login_or_not
    confirm = self.wait.until(EC.presence_of_element_located((
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

xuexi successfully!
请按任意键继续. . .

不知道是什么原因？另外能否设定每次登录的时候如果加参数的话就强制按照参数指定的用户名和密码进行登录那？因为单位每人要负责3个强国号的任务，如果可以的话，就不用每次都先进强国换用户名和密码了！建三个批处理文件就能解决问题！

**Comment by kessil** [comment]
不支持logout

**Comment by hydjq** [comment]
那能否在学习完成以后加入直接退出当前的用户，这样每次进入的时候就可以用加参数的方式进入了！

**Comment by hydjq** [comment]
不支持注销，刚看明白，谢谢了！现在这样已经很感谢了！麻烦点就麻烦点吧！再次感谢！致敬！致敬！
