### ISSUE TITLE
带参数运行出错!

### ISSUE THREAD

**Issue by hydjq** [kessil/AutoXue#156]
最新版的终于支持注销功能了，这对我们每个人有三个任务的真是一大福音，深深的感谢！反馈一下带参数运行时出现的问题，望大神测试是否存在相同的问题，我是1、将setup.cmd 文件中的venv\scripts\python -m xuexi -u "user" -p "password" 进行了修改，2、按照您的说明修改custom.ini中的keep_alive = false 测试的，可以进行自动登录，但登录后直接闪退，并出现如下错误，但如果是提前登录了，则正常运行，结束后自动注销！谢谢！谢谢
![QQ截图20200101171029](https://user-images.githubusercontent.com/33923598/71639949-0f46e680-2cbc-11ea-8b23-31db84265057.png)
![02](https://user-images.githubusercontent.com/33923598/71639950-179f2180-2cbc-11ea-806d-1df6cc6f8249.png)
![03](https://user-images.githubusercontent.com/33923598/71639953-1c63d580-2cbc-11ea-97e3-3dd919d01d47.png)

**Comment by hydjq** [comment]
错误提示：
C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev
Appium.exe                    5680 Console                    1    160,156 K
Appium.exe                    6104 Console                    1     41,888 K
Appium.exe                    9012 Console                    1    122,552 K
Nox.exe                       7504 Console                    1     21,864 K
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__main__.py", line 22, in <module>
    app = App(args.username, args.password)
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__init__.py", line 145, in __init__
    self.login_or_not()
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi\__init__.py", line 181, in login_or_not
    confirm = self.wait.until(EC.presence_of_element_located((
  File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

xuexi successfully!
请按任意键继续. . .

**Comment by hydjq** [comment]
老大，这个问题也一并修复下吧，难道是个例吗？我在3台机器上安装出现的都是同样的问题！！

**Comment by hydjq** [comment]
@kessil  老大，这个问题也一并修复下吧，难道是个例吗？我在3台机器上安装出现的都是同样的问题！！

**Comment by zz803abc** [comment]
> 错误提示：
> C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev
> Appium.exe 5680 Console 1 160,156 K
> Appium.exe 6104 Console 1 41,888 K
> Appium.exe 9012 Console 1 122,552 K
> Nox.exe 7504 Console 1 21,864 K
> [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> adb server version (36) doesn't match this client (41); killing...
> 
> * daemon started successfully
>   [INFO] 模拟器 127.0.0.1:62001 连接成功
>   [INFO] 打开 appium 服务,正在配置...
>   Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
>   return _run_code(code, main_globals, None,
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
>   exec(code, run_globals)
>   File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi__main__.py", line 22, in 
>   app = App(args.username, args.password)
>   File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi__init__.py", line 145, in **init**
>   self.login_or_not()
>   File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\xuexi__init__.py", line 181, in login_or_not
>   confirm = self.wait.until(EC.presence_of_element_located((
>   File "C:\Users\Administrator\Desktop\AutoXue-dev\AutoXue-dev\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
>   raise TimeoutException(message, screen, stacktrace)
>   selenium.common.exceptions.TimeoutException: Message:
> 
> xuexi successfully!
> 请按任意键继续. . .

我也遇到了同样的问题，你是怎么解决的？？

**Comment by hydjq** [comment]
@kessil  感谢感谢！昨天使用，问题已经解决了！但是学不满分，文章时长和视频时长都不满！明天再试一下看看
