### ISSUE TITLE
关于每日答题填空题答错后报错不会点击下一题

### ISSUE THREAD

**Issue by hnsdzhouxiao** [kessil/AutoXue#162]
每日答题填空题答错后，会出现报错，不会点击下一题

**Comment by hnsdzhouxiao** [comment]
空格数 2
空格数 2
[INFO] 填空题 汉语文出版物以及信息处理和信息技术产品中使用的国家通用语言文字应当符合国家通用语言文字的  和  。
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\AutoXue-dev\xuexi\__main__.py", line 50, in <module>
    start()
  File "E:\AutoXue-dev\xuexi\__main__.py", line 35, in start
    shuffle([app.read, app.daily, app.challenge])
  File "E:\AutoXue-dev\xuexi\__main__.py", line 27, in shuffle
    func()
  File "E:\AutoXue-dev\xuexi\__init__.py", line 712, in daily
    self._daily(self.daily_count)
  File "E:\AutoXue-dev\xuexi\__init__.py", line 675, in _daily
    self._dispath()
  File "E:\AutoXue-dev\xuexi\__init__.py", line 661, in _dispath
    self._blank()
  File "E:\AutoXue-dev\xuexi\__init__.py", line 525, in _blank
    answer = self._verify("填空题", content, "") #
  File "E:\AutoXue-dev\xuexi\__init__.py", line 289, in _verify
    return " ".join(result)
TypeError: sequence item 0: expected str instance, tuple found
xuexi successfully!
请按任意键继续. . .

**Comment by xunzh2000** [comment]
配置里
rule_submit = //node[@Class="android.widget.Button"]/@bounds
改为
rule_submit = //node[@content-desc="确定"]/@bounds

**Comment by xunzh2000** [comment]
config-default.ini

**Comment by kessil** [comment]
这个问题是已知的，填空题超过一个空的话，查看提示使用正则匹配会抛出错误，由于这种填空题很少，复现困难，一直无法修复。重试就好了，祈祷不要遇到这样的填空题吧

**Comment by izmao** [comment]
我自己加了一段程序
        try:
            submit_anser = self.driver.find_element_by_xpath(rules["daily_submit"])
            submit_anser.click()
        except NoSuchElementException as e:
            logger.info("没有可点击的【确定】按钮")
        time.sleep(3)
        try:
            submit_next = self.driver.find_element_by_xpath(rules["daily_submit_next"])
            submit_next.click()
        except NoSuchElementException as e:
            logger.info("没有可点击的【下一题】按钮")

**Comment by hnsdzhouxiao** [comment]
之前不是一直都是超过两个空格查看不到答案会评论英文字母然后下一题吗
