### ISSUE TITLE
求助：出现这个报错

### ISSUE THREAD

**Issue by daisl77** [kessil/AutoXue#174]
![image](https://user-images.githubusercontent.com/60877992/74144023-e7da2680-4c36-11ea-8fda-706d4f5c0596.png)

**Comment by daisl77** [comment]
[INFO] 挑战答题积分已达成，无需重复挑战
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__main__.py", line 50, in <module>
    start()
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__main__.py", line 35, in start
    shuffle([app.read, app.daily, app.challenge])
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__main__.py", line 27, in shuffle
    func()
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__init__.py", line 859, in read
    self._kaleidoscope()
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__init__.py", line 845, in _kaleidoscope
    self.safe_click(rules['article_kaleidoscope'])
  File "D:\Users\Administrator\Downloads\AutoXue-dev\xuexi\__init__.py", line 122, in safe_click
    button = self.wait.until(EC.presence_of_element_located((By.XPATH, ele)))
  File "D:\Users\Administrator\Downloads\AutoXue-dev\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

xuexi successfully!

**Comment by daisl77** [comment]
解决了，是我的学习强国版本不够新

**Comment by daisl77** [comment]
解决了，因为我没订阅过

**Comment by cedar-c** [comment]
对于二次启动我有一点小技巧，因为不太了解这个脚本语言，不知道里面怎么用if语句。
参考了作者的原start，我做了一点修改可以达到二次启动的目的，当然代码肯定不是最优的，有大佬知道怎么改的给个建议。
:run
REM echo venv\scripts\python -m xuexi
venv\scripts\python -m xuexi

REM echo venv\scripts\python -m xuexi
venv\scripts\python -m xuexi
echo xuexi successfully!
pause
exit

我把run改了一下，就行相当于又让它运行了一次
REM echo venv\scripts\python -m xuexi
venv\scripts\python -m xuexi
，测试是可以的，也就是说你如果想让它来三次，那就加两遍。
当然如果能用if写就更好了，但是我不会。哈哈哈哈。
ps：打开start.cmd进行更改

**Comment by kessil** [comment]
就目前了解，挑战答题结束可能导致异常退出，结束机制或有改动，没去定位问题，了解情况的欢迎回复，周末有时间尝试修复。如果确实存在其他频繁异常退出情况，也可以反馈，但是请不要丢一张图片给我。

**Comment by cedar-c** [comment]
挑战答题好像是多了一个结束弹窗

**Comment by Takea3** [comment]
:run
REM echo venv\scripts\python -m xuexi
venv\scripts\python -m xuexi -u "13102387805" -p "67288412we"
TIMEOUT /T 10
for /f "delims=" %%i in ('powershell -c "Get-Date -UFormat '%%Y-%%m-%%d'"') do (set "SysTS=%%i")
set str=%cd%\logs\%SysTS%.log
echo %str%
for /f "delims=" %%a in (%str%) do set str1=%%~a
If NOT "%str1%"=="%str1:logout_or_not=%" (echo bunengyongzhongwen) else goto run
pause
exit



我搞定了，，，拿去吧。。

**Comment by Takea3** [comment]
:run
REM echo venv\scripts\python -m xuexi
venv\scripts\python -m xuexi
TIMEOUT /T 10
for /f "delims=" %%i in ('powershell -c "Get-Date -UFormat '%%Y-%%m-%%d'"') do (set "SysTS=%%i")
set str=%cd%\logs\%SysTS%.log
echo %str%
for /f "delims=" %%a in (%str%) do set str1=%%~a
If NOT "%str1%"=="%str1:logout_or_not=%" (echo bunengyongzhongwen) else goto run
pause
exit

我搞定了，，拿去吧。。

**Comment by cedar-c** [comment]
> :run
> REM echo venv\scripts\python -m xuexi
> venv\scripts\python -m xuexi
> TIMEOUT /T 10
> for /f "delims=" %%i in ('powershell -c "Get-Date -UFormat '%%Y-%%m-%%d'"') do (set "SysTS=%%i")
> set str=%cd%\logs%SysTS%.log
> echo %str%
> for /f "delims=" %%a in (%str%) do set str1=%%~a
> If NOT "%str1%"=="%str1:logout_or_not=%" (echo bunengyongzhongwen) else goto run
> pause
> exit
> 
> 我搞定了，，拿去吧。。

少了一个斜杠导致日志读取不到
`> set str=%cd%\logs%SysTS%.log`
这里要改成
`> set str=%cd%\logs\%SysTS%.log`
