### ISSUE TITLE
selenium  webdriver 超时错误TimeoutException  

### ISSUE THREAD

**Issue by big3er** [kessil/AutoXue#176]
[INFO] 模拟器 emulator-5554 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/windy/Desktop/AutoXue/xuexi/__main__.py", line 17, in <module>
    app = App()
  File "/Users/windy/Desktop/AutoXue/xuexi/__init__.py", line 120, in __init__
    self.view_score()
  File "/Users/windy/Desktop/AutoXue/xuexi/__init__.py", line 125, in view_score
    self.safe_click(rules['score_entry'])
  File "/Users/windy/Desktop/AutoXue/xuexi/__init__.py", line 101, in safe_click
    self.wait.until(EC.presence_of_element_located((By.XPATH, ele))).click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by cedar-c** [comment]
一般这种情况应该是延时少了。就是你的延时到了，但是你的页面还没有加载出来。

**Comment by kessil** [comment]
注意观察点击之前主页是否已刷新出来
