### ISSUE TITLE
每日答题规则改变了！

### ISSUE THREAD

**Issue by hydjq** [kessil/AutoXue#179]
感谢老大辛勤付出！发现2个问题反馈一下：
1、从昨天开始每日答题的规则由之前的每组5个题改成10个题，得分规则由之前的每次2分改成了答对6题直接得6分，答题进行不下去了，所有步骤就停了，想问一下有没有答题模块的参数？比如出现这种问题后可以加参数运行，先跳过每日答题，将其他项目进行完；
2、进行挑战答题时经常会先跳出一个调整字体的对话框，导致答题失败，这个对话框随机性很大，有时候2,3天出一次，有时候一个星期出现一次；

建议：能否将每个模块独立化运行，现在的运行模式是顺序话，只要那个项目出现问题了，下面所有的项目就停止运行了，能否在运行分模块时如果那个模块出现了错误，也只是其中的一个一项终止，其他的项目继续运行，只是建议，本来就是都给了自行车了还要啥手表，已经很知足，十分感谢老大的无私奉献！

**Comment by cedar-c** [comment]
暂时性的解决办法，在init里面每日答题模块第441行代码处把5改成10.也就是改成这样：self.count_of_each_group = 10
相当于把一组的题目数由5改成了10，当然这样的代码肯定不精简，但是暂时可以用。

**Comment by zz803abc** [comment]
> 暂时性的解决办法，在init里面每日答题模块第441行代码处把5改成10.也就是改成这样：self.count_of_each_group = 10
> 相当于把一组的题目数由5改成了10，当然这样的代码肯定不精简，但是暂时可以用。

感谢，相当好使！！

**Comment by hydjq** [comment]
好的，我今天是先把每日答题打完后，再运行的程序，已经修改，明天试试！谢谢！

**Comment by xunzh2000** [comment]
> 暂时性的解决办法，在init里面每日答题模块第441行代码处把5改成10.也就是改成这样：self.count_of_each_group = 10
> 相当于把一组的题目数由5改成了10，当然这样的代码肯定不精简，但是暂时可以用。

没有找到文件路径，能不能指点一下。另外我的现在一开每日答题，就提示未知题型，然后报错。请问怎么回事？谢谢

**Comment by tonylemon** [comment]
> 暂时性的解决办法，在xuexi文件夹中 _init_.py 里面每日答题模块第441行代码处把5改成10.也就是改成这样：self.count_of_each_group = 10
> 相当于把一组的题目数由5改成了10，当然这样的代码肯定不精简，而且可能有其他问题(我暂时没遇到），但是暂时可以用。

你好，顺便请教下在xuexi文件夹中 _init_.py 里面每日答题模块670行672行代码 num（组） 值怎么来得？看日志直接是第5组开始的，不懂。谢谢！

**Comment by hnsdzhouxiao** [comment]
挑战答题的答题结束也变了

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\AutoXue-dev\xuexi\__main__.py", line 50, in <module>
    start()
  File "E:\AutoXue-dev\xuexi\__main__.py", line 39, in start
    shuffle([app.read, app.daily, app.challenge])
  File "E:\AutoXue-dev\xuexi\__main__.py", line 27, in shuffle
    func()
  File "E:\AutoXue-dev\xuexi\__init__.py", line 709, in daily
    self.safe_click(rules['mine_entry'])
  File "E:\AutoXue-dev\xuexi\__init__.py", line 122, in safe_click
    button = self.wait.until(EC.presence_of_element_located((By.XPATH, ele)))
  File "E:\AutoXue-dev\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

xuexi successfully!

**Comment by q123458384** [comment]
> group
新版还是旧版的？我这没有intit.py
只有 _intit_.py
里面只有306行 没有“self.count_of_each_group = ”

**Comment by cedar-c** [comment]
> > 暂时性的解决办法，在xuexi文件夹中 _init_.py 里面每日答题模块第441行代码处把5改成10.也就是改成这样：self.count_of_each_group = 10
> > 相当于把一组的题目数由5改成了10，当然这样的代码肯定不精简，而且可能有其他问题(我暂时没遇到），但是暂时可以用。
> 
> 你好，顺便请教下在xuexi文件夹中 _init_.py 里面每日答题模块670行672行代码 num（组） 值怎么来得？看日志直接是第5组开始的，不懂。谢谢！

讲道理我也看的一知半解，不敢乱说。
