### ISSUE TITLE
版主 能把之前的版本也更新一下吗  每日答题和挑战答题也出问题

### ISSUE THREAD

**Issue by papa-cmd** [kessil/AutoXue#180]
求助啊  以前的版本  用的一直是以前的版本

**Comment by xunzh2000** [comment]
我也是老版，拜托了，现在每日答题无法做，提示未知类型题目。

**Comment by fuckxszy** [comment]
肯定不会啊。。装个新版不香么

**Comment by 17837697** [comment]
> 我也是老版，拜托了，现在每日答题无法做，提示未知类型题目。
因为题目数量变化了，所以需要修改xpath匹配原则

修改config-default.ini里面的匹配原则
把每日答题里面的"1 /5"这种都改成"1 /10"就可以了，别忘了补充够10个

**Comment by kessil** [comment]
不好意思旧版库遗失了，当前环境也不支持旧版。可以尝试楼上的方案。

**Comment by q123458384** [comment]
> > 我也是老版，拜托了，现在每日答题无法做，提示未知类型题目。
> > 因为题目数量变化了，所以需要修改xpath匹配原则
> 
> 修改config-default.ini里面的匹配原则
> 把每日答题里面的"1 /5"这种都改成"1 /10"就可以了，别忘了补充够10个

[填空题] ...
Traceback (most recent call last):
  File "C:\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\xxqg\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\xxqg\AutoXue-master\xuexi\__init__.py", line 62, in start
    self._quiz_run(day, chg)
  File "D:\xxqg\AutoXue-master\xuexi\__init__.py", line 57, in _quiz_run
    qApp.start(day, chg)
  File "D:\xxqg\AutoXue-master\xuexi\quiz\__init__.py", line 72, in start
    self._run_daily()
  File "D:\xxqg\AutoXue-master\xuexi\quiz\__init__.py", line 38, in _run_daily
    dq.run()
  File "D:\xxqg\AutoXue-master\xuexi\quiz\daily.py", line 269, in run
    self._dispatch()
  File "D:\xxqg\AutoXue-master\xuexi\quiz\daily.py", line 239, in _dispatch
    self._blank()
  File "D:\xxqg\AutoXue-master\xuexi\quiz\daily.py", line 67, in _blank
    logger.info(f'自动提交答案: {bank.answer}')
AttributeError: 'list' object has no attribute 'answer'
(⊙﹏⊙) 不懂怎么改

**Comment by xunzh2000** [comment]
改为，如下，@content-desc="1 /10" or @content-desc="2 /10" or @content-desc="3 /10" or @content-desc="4 /10" or @content-desc="5 /10" or @content-desc="6 /10" or @content-desc="7 /10" or @content-desc="8 /10" or @content-desc="9 /10" or @content-desc="10 /10"
好几处都改。可以的，谢谢楼上大侠。

**Comment by zzzzzqf** [comment]
> 肯定不会啊。。装个新版不香么

新版只能挑战答题，其他的功能好像没有啊，怎么弄。。。
