### ISSUE TITLE
挑战答题还是偶尔出问题，16号的最新版本。

### ISSUE THREAD

**Issue by LINGJULIDEHUIMOU** [kessil/AutoXue#191]
<img width="734" alt="Snipaste_2020-03-17_00-29-16" src="https://user-images.githubusercontent.com/54373657/76779489-669e2280-67e6-11ea-9149-b7dab764bea5.png">

**Comment by extranquil** [comment]
same here

**Comment by kessil** [comment]
十分遗憾发生上述错误，作者本地测试无异常，是否模拟器卡顿或网络因素造成，频繁发生请描述具体情况，将尽力为你解答。

**Comment by extranquil** [comment]
emm，具体情况就是一般是学完某一个功能比如百灵视频后跳exception，或是挑战答题或每日答题进行了3、4题之后跳相同错误。log中则是报“Remote end closed connection without response”。目测应该不是卡顿或者网络加载问题，尝试过把init.py中所有self.driver.findelement/elements前都加上sleep(1)也未能解决问题。

模拟器是Nox，Android版本5.1.1，SDK版本都是最新版，同时也替换了nox中的adb。

例如今天这次：

[INFO] 正在观看视频 <2#> 34 秒进入下一则...
[INFO] 正在观看视频 <1#> 27 秒进入下一则...
[INFO] 正在观看视频 <0#> 25 秒进入下一则...
[INFO] 视听学习完毕，正在返回...
Traceback (most recent call last):
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AutoXue\xuexi\__main__.py", line 51, in <module>
    start()
  File "D:\AutoXue\xuexi\__main__.py", line 36, in start
    shuffle([app.read, app.daily, app.challenge, app.weekly])
  File "D:\AutoXue\xuexi\__main__.py", line 28, in shuffle
    func()
  File "D:\AutoXue\xuexi\__init__.py", line 864, in read
    self._kaleidoscope()
  File "D:\AutoXue\xuexi\__init__.py", line 850, in _kaleidoscope
    self.safe_click(rules['article_kaleidoscope'])
  File "D:\AutoXue\xuexi\__init__.py", line 125, in safe_click
    button = self.wait.until(EC.presence_of_element_located((By.XPATH, ele)))
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "D:\AutoXue\venv\lib\site-packages\appium\webdriver\webdriver.py", line 282, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "D:\AutoXue\venv\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "D:\AutoXue\venv\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\AutoXue\venv\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "D:\AutoXue\venv\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\AutoXue\venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\AutoXue\venv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\extra\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
请按任意键继续. . .

**Comment by kessil** [comment]
不排除问题出现在`safe_back`,待排查

**Comment by DrMewo** [comment]
同样的问题同样的情况发生，答完每日答题之后准备看新闻时出现
最后一条log [2020-03-31 08:00:01,757][DEBUG][__init__.py][safe_click][124]: safe click //android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.ImageView

**Comment by extranquil** [comment]
最近尝试过在某些位置加time.sleep，没有解决问题。
观察了一下，应该不是safe_back的问题，因为很多次都是在填空题填好答案后，或选择题点击选项后，在点击确认之前（或点击时）出现问题。
出现问题的位置不固定，频率不固定，每日答题、挑战答题、文章阅读时或模块结束后都有可能出现，但百灵视频貌似没问题，通常可以一刷到底。

**Comment by extranquil** [comment]
好厉害哦，最近一次pull之后，题库API修好以后就再也没有出现过报错了，已连续2天一做到底。

**Comment by shajia1992** [comment]
> 十分遗憾发生上述错误，作者本地测试无异常，是否模拟器卡顿或网络因素造成，频繁发生请描述具体情况，将尽力为你解答。

带佬可以指点一下这个环境变量的配置安装么，教程还是有点看不懂
