### ISSUE TITLE
请问是要使用dev分支么？

### ISSUE THREAD

**Issue by geminisnow** [kessil/AutoXue#206]
请教大神，master分支只能挑战答题，如果想实现每周答题等功能是要更新什么东西么？
试了下dev分支，模拟器打开app就报错“未提供有效的username和password”，试着在start.cmd里面加了-u-p把用户名和密码写上去后可以打开app，但是跑一段代码后app就自动退出了。
请教该怎么处理？多谢

**Comment by kessil** [comment]
有日志吗？

**Comment by geminisnow** [comment]
> 有日志吗？

劳烦大神费心了，好像是登录的问题，但是我已在cmd中加入了用户名密码，以下是日志：

[2020-04-27 12:55:05,681][INFO][__init__.py][connect][ 52]: 正在连接模拟器 127.0.0.1:62001，请稍候...
[2020-04-27 12:55:05,716][INFO][__init__.py][connect][ 54]: 模拟器 127.0.0.1:62001 连接成功
[2020-04-27 12:55:05,717][INFO][__init__.py][__init__][ 46]: 打开 appium 服务,正在配置...
[2020-04-27 12:55:33,183][DEBUG][__init__.py][login_or_not][163]: com.alibaba.android.rimet.biz.SplashActivity
[2020-04-27 12:55:33,183][DEBUG][__init__.py][login_or_not][164]: Not home page, login first!

以下是cmd窗口：
Traceback (most recent call last):
  File "C:\Users\New\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\New\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Software\xuexi2\AutoXue\xuexi\__main__.py", line 23, in <module>
    app = App(args.username, args.password)
  File "C:\Software\xuexi2\AutoXue\xuexi\__init__.py", line 146, in __init__
    self.login_or_not()
  File "C:\Software\xuexi2\AutoXue\xuexi\__init__.py", line 173, in login_or_not
    By.XPATH, rules["login_username"]
  File "C:\Software\xuexi2\AutoXue\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by kessil** [comment]
> > 有日志吗？
> 
> 劳烦大神费心了，好像是登录的问题，但是我已在cmd中加入了用户名密码，以下是日志：
> 
> [2020-04-27 12:55:05,681][INFO][**init**.py][connect][ 52]: 正在连接模拟器 127.0.0.1:62001，请稍候...
> [2020-04-27 12:55:05,716][INFO][**init**.py][connect][ 54]: 模拟器 127.0.0.1:62001 连接成功
> [2020-04-27 12:55:05,717][INFO][**init**.py][**init**][ 46]: 打开 appium 服务,正在配置...
> [2020-04-27 12:55:33,183][DEBUG][**init**.py][login_or_not][163]: com.alibaba.android.rimet.biz.SplashActivity
> [2020-04-27 12:55:33,183][DEBUG][**init**.py][login_or_not][164]: Not home page, login first!
> 
> 以下是cmd窗口：
> Traceback (most recent call last):
> File "C:\Users\New\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Users\New\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Software\xuexi2\AutoXue\xuexi__main__.py", line 23, in app = App(args.username, args.password) File "C:\Software\xuexi2\AutoXue\xuexi__init__.py", line 146, in **init**
> self.login_or_not()
> File "C:\Software\xuexi2\AutoXue\xuexi__init__.py", line 173, in login_or_not
> By.XPATH, rules["login_username"]
> File "C:\Software\xuexi2\AutoXue\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
> raise TimeoutException(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message:

获取username控件失败，建议提前在app登录好账号，则无需添加-u -p参数即可运行
