### ISSUE TITLE
第一次接触这个软件，运行报错，请大佬指点，本人小白一个。

### ISSUE THREAD

**Issue by liukangyi2019** [kessil/AutoXue#215]
F:\BaiduNetdiskDownload\python_work\AutoXue-master
Appium.exe                    7568 Console                    1    152,608 K
Appium.exe                    7876 Console                    1     18,040 K
Appium.exe                    7956 Console                    1     18,816 K
Appium is running
Nox.exe                       1352 Console                    1     27,920 K
Nox is running
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "E:\my_work\python3.8.3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\my_work\python3.8.3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi\__main__.py", l
ine 17, in <module>
    app = App()
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi\__init__.py", l
ine 118, in __init__
    super().__init__()
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi\__init__.py", l
ine 44, in __init__
    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', self.desired_
caps)
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
s\appium\webdriver\webdriver.py", line 151, in __init__
    super().__init__(
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
s\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
s\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side e
rror occurred while processing the command. Original error: Could not find adb.e
xe in E:\my_work\sdk\platform-tools\adb.exe,E:\my_work\sdk\emulator\adb.exe,E:\m
y_work\sdk\tools\adb.exe,E:\my_work\sdk\tools\bin\adb.exe. Do you have the Andro
id SDK installed at 'E:\my_work\sdk'?

Exception ignored in: <function Automation.__del__ at 0x00000000034F0AF0>
Traceback (most recent call last):
  File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi\__init__.py", l
ine 105, in __del__
    self.driver.close_app()
AttributeError: 'App' object has no attribute 'driver'
xuexi successfully!
请按任意键继续. . .

**Comment by jarrowkidd** [comment]
一样的问题，求解

**Comment by shajia1992** [comment]
> F:\BaiduNetdiskDownload\python_work\AutoXue-master
> Appium.exe 7568 Console 1 152,608 K
> Appium.exe 7876 Console 1 18,040 K
> Appium.exe 7956 Console 1 18,816 K
> Appium is running
> Nox.exe 1352 Console 1 27,920 K
> Nox is running
> [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> [INFO] 模拟器 127.0.0.1:62001 连接成功
> [INFO] 打开 appium 服务,正在配置...
> Traceback (most recent call last):
> File "E:\my_work\python3.8.3\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "E:\my_work\python3.8.3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi__main__.py", l ine 17, in app = App() File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi__init__.py", l ine 118, in **init** super().**init**() File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi__init__.py", l
> ine 44, in **init**
> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', self.desired_
> caps)
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
> s\appium\webdriver\webdriver.py", line 151, in **init**
> super().**init**(
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
> s\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
> s\appium\webdriver\webdriver.py", line 225, in start_session
> response = self.execute(RemoteCommand.NEW_SESSION, parameters)
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
> s\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\venv\lib\site-package
> s\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> [selenium.com](selenium.com)mon.exceptions.WebDriverException: Message: An unknown server-side e
> rror occurred while processing the command. Original error: Could not find adb.e
> xe in E:\my_work\sdk\platform-tools\adb.exe,E:\my_work\sdk\emulator\adb.exe,E:\m
> y_work\sdk\tools\adb.exe,E:\my_work\sdk\tools\bin\adb.exe. Do you have the Andro
> id SDK installed at 'E:\my_work\sdk'?
> 
> Exception ignored in: <function Automation.**del** at 0x00000000034F0AF0>
> Traceback (most recent call last):
> File "F:\BaiduNetdiskDownload\python_work\AutoXue-master\xuexi__init__.py", l
> ine 105, in **del**
> self.driver.close_app()
> AttributeError: 'App' object has no attribute 'driver'
> xuexi successfully!
> 请按任意键继续. . .


带佬可以指点一下这个环境变量的配置安装么，教程还是有点看不懂

**Comment by shajia1992** [comment]
> 一样的问题，求解

带佬可以指点一下这个环境变量的配置安装么，教程还是有点看不懂
