### ISSUE TITLE
已配置好，但检测不到adb.exe 报错 Do you have Android Build Tools installed

### ISSUE THREAD

**Issue by cjh0613** [kessil/AutoXue#216]
win10 x64

python 3.8.3 x86

已安装好全部依赖并按说明配置环境变量并更新

使用`android studio` 安装的 `API Level 21&29 sdk`

但还是检测不到adb.exe：

```
E:\GitHub\AutoXue
Appium.exe                   10848 Console                    3    168,592 K
Appium.exe                   14252 Console                    3     59,216 K
Appium.exe                    9936 Console                    3    124,348 K
Appium is running
Nox.exe                       7856 Console                    3     32,072 K
Nox is running
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\GitHub\AutoXue\xuexi\__main__.py", line 17, in <module>
    app = App()
  File "E:\GitHub\AutoXue\xuexi\__init__.py", line 118, in __init__
    super().__init__()
  File "E:\GitHub\AutoXue\xuexi\__init__.py", line 44, in __init__
    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', self.desired_caps)
  File "E:\GitHub\AutoXue\venv\lib\site-packages\appium\webdriver\webdriver.py", line 151, in __init__
    super().__init__(
  File "E:\GitHub\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "E:\GitHub\AutoXue\venv\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "E:\GitHub\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "E:\GitHub\AutoXue\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\CJH\\AppData\\Local\\Android\\Sdk\\;\\platform-tools\\adb.exe","C:\\Users\\CJH\\AppData\\Local\\Android\\Sdk\\;\\emulator\\adb.exe","C:\\Users\\CJH\\AppData\\Local\\Android\\Sdk\\;\\tools\\adb.exe","C:\\Users\\CJH\\AppData\\Local\\Android\\Sdk\\;\\tools\\bin\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\CJH\AppData\Local\Android\Sdk\;'?

Exception ignored in: <function Automation.__del__ at 0x041BBAD8>
Traceback (most recent call last):
  File "E:\GitHub\AutoXue\xuexi\__init__.py", line 105, in __del__
    self.driver.close_app()
AttributeError: 'App' object has no attribute 'driver'
xuexi successfully!
请按任意键继续. . .
```

**Comment by kessil** [comment]
请在cmd窗口输入 `adb version` 验证adb安装是否成功，输入 `adb devices -l` 验证连接模拟器是否成功

**Comment by cjh0613** [comment]
> 请在cmd窗口输入 `adb version` 验证adb安装是否成功，输入 `adb devices -l` 验证连接模拟器是否成功

已通过用模拟器adb替换下载的adb.exe修复无法连接模拟器问题。但报上方同样的错误。

```
C:\WINDOWS\system32>adb version
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android

C:\WINDOWS\system32>adb devices -l
List of devices attached
127.0.0.1:62001        device product:heroltektt model:SM_G930K device:shamu
```

给adb.exe设置管理员方式启动后，运行start.cmd有adb.exe请求管理员的提示，说明可以找到。

另外希望增加直接指定adb.exe的设置， 因下载的adb有他用。

**Comment by cjh0613** [comment]
找到问题，ANDROID_HOME结尾配置错误，运行%ANDROID_HOME%无法打开文件夹

**Comment by cjh0613** [comment]
@kessil  程序很好，已给star，我有空会在此基础上升个级、优化软件安装流程。

**Comment by hpzka** [comment]
这个能自动视频学习嘛

**Comment by shajia1992** [comment]
> @kessil 程序很好，已给star，我有空会在此基础上升个级、优化软件安装流程。

期待老哥优化，目前用着还是不太稳定，容易闪退
