### ISSUE TITLE
作者可以更新一下了，新版本又开始报错了。

### ISSUE THREAD

**Issue by solife2020** [kessil/AutoXue#223]

**Comment by kessil** [comment]
由于电脑使用WSL，无法使用模拟器。请详细说明一下报错细节。

**Comment by little-happypig** [comment]
Traceback (most recent call last):
  File "C:\Users\Long\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Long\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\VS Projects\AutoXue\xuexi\__main__.py", line 51, in <module>
    start()
  File "D:\VS Projects\AutoXue\xuexi\__main__.py", line 42, in start
    app.logout_or_not()
  File "D:\VS Projects\AutoXue\xuexi\__init__.py", line 196, in logout_or_not
    self.safe_click(rules["mine_entry"])
  File "D:\VS Projects\AutoXue\xuexi\__init__.py", line 123, in safe_click
    button = self.wait.until(EC.presence_of_element_located((By.XPATH, ele)))
  File "D:\VS Projects\AutoXue\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

请按任意键继续. . .

**Comment by little-happypig** [comment]
每周答题还有好多没答的，现在不能答了

**Comment by little-happypig** [comment]
谢谢
