### ISSUE TITLE
APP更新后，不好用了。

### ISSUE THREAD

**Issue by hyy34** [kessil/AutoXue#24]
安卓，一直使用1.0的版本，今天将APP升级了，但是程序不好用了。

C:\venv>python main.py
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    cfg.read('./default.ini')
  File "G:\Python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "G:\Python\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence

以上是老版

**Comment by hyy34** [comment]
C:\venv>python daily.py
running init func...
running start func...
running enter func...
2674 KB/s (43792 bytes in 0.015s)
Traceback (most recent call last):
  File "daily.py", line 265, in <module>
    daily.start()
  File "daily.py", line 246, in start
    self.enter()
  File "daily.py", line 106, in enter
    pos = self._get_bounds(self.news_goto_study, True)[0]
IndexError: list index out of range

**Comment by hyy34** [comment]
新版的APP，首页布局改变了。

**Comment by hyy34** [comment]
C:\venv>python daily.py
running init func...
running start func...
running enter func...
3276 KB/s (43749 bytes in 0.013s)
Traceback (most recent call last):
  File "daily.py", line 265, in <module>
    daily.start()
  File "daily.py", line 246, in start
    self.enter()
  File "daily.py", line 106, in enter
    pos = self._get_bounds(self.news_goto_study, True)[0]
IndexError: list index out of range

**Comment by hyy34** [comment]
确认本机adb.exe版本号为最新版本[ADB 1.0.40]

如何查看我winPC本机的ADB版本号呢。我是在1.0的时候安装的ADB。

**Comment by wo900316** [comment]
me too

**Comment by kessil** [comment]
更新UI不局确实造成每日答题失效，将在下个版本中修复，敬请期待

**Comment by hyy34** [comment]
> 更新UI不局确实造成每日答题失效，将在下个版本中修复，敬请期待

C:\venv>python main.py
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    cfg.read('./default.ini')
  File "G:\Python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "G:\Python\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence
 挑战答题是不是也不好用呢？我出现这个错误。

**Comment by hyy34** [comment]
> me too

挑战是不是也不好用了！？

**Comment by hyy34** [comment]
C:\venv>python main.py
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    start(device, count_question, filename, database_uri, delay_seconds, user_agent)
  File "main.py", line 52, in start
    question = Bank.from_xml(device)
  File "C:\venv\model.py", line 49, in from_xml
    cfg.read('./default.ini')
  File "G:\Python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "G:\Python\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence

为什么还有这个提示呢？哪弄的不对呢？

**Comment by hyy34** [comment]
C:\venv>python main.py
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    start(device, count_question, filename, database_uri, delay_seconds, user_agent)
  File "main.py", line 52, in start
    question = Bank.from_xml(device)
  File "C:\venv\model.py", line 49, in from_xml
    cfg.read('./default.ini')
  File "G:\Python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "G:\Python\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence

大佬，一直是这个提示。。如何解决呢！？回个话被。

**Comment by kessil** [comment]
请看新分支dev
