### ISSUE TITLE
手机连接电脑程序执行错误

### ISSUE THREAD

**Issue by squirrelmedia** [kessil/AutoXue#34]
### 操作都正常，打开程序放在QG首页，程序执行到点击“我的”图标后出现以下错误
```
Let's Go!

        阅读文章[√]    视听学习[√]    每日答题[√]    挑战答题[√]

连接模拟器127.0.0.1:7555 成功
阅读文章功能正在实现中
视听学习功能正在实现中
1322 KB/s (21212 bytes in 0.015s)
3129 KB/s (21212 bytes in 0.006s)
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__init__.py", line 56, in start
    self._quiz_run(day, chg)
  File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__init__.py", line 47, in _quiz_run
    qApp.start(day, chg)
  File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\quiz\__init__.py", line 68, in start
    self.ad.tap(pos)
  File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\common\adble.py", line 117, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .
```

> 使用MuMu模拟器运行没有问题

**Comment by kessil** [comment]
【我的】页面下内容在手机上是放在一个容器里面，用uiautomator获取不到布局，所以解析不到【我要答题】的坐标

**Comment by wo900316** [comment]
> 【我的】页面下内容在手机上是放在一个容器里面，用uiautomator获取不到布局，所以解析不到【我要答题】的坐标

写个手机调试模式的教程吧，我也是上述错误提示

**Comment by cz1980** [comment]
> 
> 
> 【我的】页面下内容在手机上是放在一个容器里面，用uiautomator获取不到布局，所以解析不到【我要答题】的坐标

开始我用手机发现xpath解析错误，发现是因为不同手机的Ui布局可能不同。于是我尝试改写xpath规则。开始改的时候，我不是作者你的xpath针对的页面的哪个元素，改不了只能作罢。后来用adb抓了ui布局文件，发现里面根本没有题目和选项等内容，可能就像你说的放在一个容器中了抓不到。后来我又改成了mumu模拟器抓了一下，发现还是没有题目和选项的内容。是不是因为我的强国app升级了的缘故？

**Comment by kessil** [comment]
mumu能抓到，其他没试

**Comment by cz1980** [comment]
我试了几次，前几次不行，后几次又可以了。

**Comment by cz1980** [comment]
> 
> ### 手机连接电脑，执行程序，出现以下错误
> ### 操作都正常，打开程序放在QG首页，程序执行到点击“我的”图标后出现以下错误
> 
> ```
> Let's Go!
> 
>         阅读文章[√]    视听学习[√]    每日答题[√]    挑战答题[√]
> 
> 连接模拟器127.0.0.1:7555 成功
> 阅读文章功能正在实现中
> 视听学习功能正在实现中
> 1322 KB/s (21212 bytes in 0.015s)
> 3129 KB/s (21212 bytes in 0.006s)
> Traceback (most recent call last):
>   File "C:\python\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\python\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__main__.py", line 41, in <module>
>     app.start(args.article, args.video, args.daily, args.challenge)
>   File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__init__.py", line 56, in start
>     self._quiz_run(day, chg)
>   File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\__init__.py", line 47, in _quiz_run
>     qApp.start(day, chg)
>   File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\quiz\__init__.py", line 68, in start
>     self.ad.tap(pos)
>   File "C:\Users\Administrator\Desktop\quizXue-master\xuexi\common\adble.py", line 117, in tap
>     dx, dy = int(x.real), int(x.imag)
> AttributeError: 'list' object has no attribute 'real'
> 断开模拟器127.0.0.1:7555 成功
> 请按任意键继续. . .
> ```
> 
> > 使用MuMu模拟器运行没有问题

我现在使用模拟器，能够进入每日答题，第一个题的时候，就出现这个错误

**Comment by 20057842** [comment]
我的MUMU正常，手机不可以华为P8

Let's Go!

        阅读文章[√]    视听学习[√]    每日答题[√]    挑战答题[√]

连接模拟器127.0.0.1:7555 成功
阅读文章功能正在实现中
视听学习功能正在实现中
Traceback (most recent call last):
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "D:\XX\quizXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 56, in start
    self._quiz_run(day, chg)
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 47, in _quiz_run
    qApp.start(day, chg)
  File "D:\XX\quizXue-master\xuexi\quiz\__init__.py", line 68, in start
    self.ad.tap(pos)
  File "D:\XX\quizXue-master\xuexi\common\adble.py", line 117, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
error: no such device '127.0.0.1:7555'
Exception ignored in: <function App.__del__ at 0x02340270>
Traceback (most recent call last):
  File "D:\XX\quizXue-master\xuexi\__init__.py", line 61, in __del__
  File "D:\XX\quizXue-master\xuexi\common\adble.py", line 135, in close
  File "D:\XX\quizXue-master\xuexi\common\adble.py", line 43, in _disconnect
  File "C:\Users\I3\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py"
, line 347, in check_call
subprocess.CalledProcessError: Command 'adb disconnect 127.0.0.1:7555' returned
non-zero exit status 1.
请按任意键继续. . .

**Comment by PerhapSC** [comment]
我的手机炸炸星没法用，MUMU可以进入，但是MUMU里始终没法调用输入法是为什么？每次要输入文字的时候就跪了，可是系统设置里明明已经打开了？
![微信图片_20190811140730](https://user-images.githubusercontent.com/17978591/62830418-61ba3480-bc41-11e9-9bfa-38e2985d9f4f.png)

**Comment by kessil** [comment]
> 
> 
> 我的手机炸炸星没法用，MUMU可以进入，但是MUMU里始终没法调用输入法是为什么？每次要输入文字的时候就跪了，可是系统设置里明明已经打开了？
> ![微信图片_20190811140730](https://user-images.githubusercontent.com/17978591/62830418-61ba3480-bc41-11e9-9bfa-38e2985d9f4f.png)

Mac MuMu? port: 5555
