### ISSUE TITLE
2.0继续出错

### ISSUE THREAD

**Issue by hyy34** [kessil/AutoXue#36]
手机模拟，2.5.0APP，运行初次安装会提示黄字：
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command
然后运行
C:\venv>python -m pip install --upgrade pip
Requirement already up-to-date: pip in g:\python\lib\site-packages (19.2.1)
点击开始积分后，出错如下：
Let's Go!

        阅读文章[√]    视听学习[√]    每日答题[√]    挑战答题[√]

连接模拟器127.0.0.1:7555 成功
阅读文章功能正在实现中
视听学习功能正在实现中
Traceback (most recent call last):
  File "G:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\venv\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\venv\xuexi\__init__.py", line 56, in start
    self._quiz_run(day, chg)
  File "C:\venv\xuexi\__init__.py", line 47, in _quiz_run
    qApp.start(day, chg)
  File "C:\venv\xuexi\quiz\__init__.py", line 68, in start
    self.ad.tap(pos)
  File "C:\venv\xuexi\common\adble.py", line 117, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
error: no such device '127.0.0.1:7555'
Exception ignored in: <function App.__del__ at 0x000001E19F700F28>
Traceback (most recent call last):
  File "C:\venv\xuexi\__init__.py", line 61, in __del__
  File "C:\venv\xuexi\common\adble.py", line 135, in close
  File "C:\venv\xuexi\common\adble.py", line 43, in _disconnect
  File "G:\Python\lib\subprocess.py", line 347, in check_call
subprocess.CalledProcessError: Command 'adb disconnect 127.0.0.1:7555' returned non-zero exit status 1.
请按任意键继续. . .

手机会点击到“我的”界面，然后出现上述错误。再次点击初次使用，还是会出现之前的错误，不知道是不是pip版本造成的。但是运行python -m pip install --upgrade pip 会提示已经安装成功，Requirement already up-to-date: pip in g:\python\lib\site-packages (19.2.1)
这个是啥问题呢！？
意见建议：试听学习，可以模拟点到下方“百灵”界面，刷新下，然后播放第一个视频，就会连续播放了，然后等待18分钟，基本上试听就能实现了。

**Comment by hyy34** [comment]
额。认真又开了一次简介，我的华为手机，估计是这个原因。。。。

**Comment by kessil** [comment]
我的华为手机，也不成功
视听学习已经实现了，和你说的基本一样，只是目前右滑退出视频偶尔不成功，所以没提交
