### ISSUE TITLE
收藏 分享出错

### ISSUE THREAD

**Issue by cheeshon** [kessil/AutoXue#39]
[01] 【新闻聚焦】山西省国土空间规划编制扎实推进...
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\runpy.py", line 193, in _r
un_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Python\Python37-32\lib\runpy.py", line 85, in _ru
n_code
    exec(code, run_globals)
  File "E:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "E:\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "E:\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "E:\AutoXue-master\xuexi\media\reader.py", line 239, in run
    self._star_share_comment(title)
  File "E:\AutoXue-master\xuexi\media\reader.py", line 121, in _star_share_comme
nt
    self.ad.tap(pos_share)
  File "E:\AutoXue-master\xuexi\common\adble.py", line 147, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by kessil** [comment]
发现有些新闻关闭评论，很不幸，你遇到的这条新闻就是关闭评论的，所以当然失败了。已修复。
