### ISSUE TITLE
试听学习出错

### ISSUE THREAD

**Issue by rzgz75069** [kessil/AutoXue#40]
答题耗时 447.82 秒
视听学习中...
Traceback (most recent call last):
  File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\Program Files\AutoXue-master\xuexi\__init__.py", line 67, in start
    self._vdo_run()
  File "D:\Program Files\AutoXue-master\xuexi\__init__.py", line 52, in _vdo_run
    vd.run(count, delay)
  File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 74, in run
    self.enter()
  File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 48, in enter
    self.ad.tap(suggest) # 点击刷新
  File "D:\Program Files\AutoXue-master\xuexi\common\adble.py", line 147, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by cedar-c** [comment]
我也是这样，答完题开始试听，然后就没了，难受

**Comment by PerhapSC** [comment]
为什么我的连答题都还没过去啊...连文字都无法输入，而且挑战答题一直答个没完了...
win10+MUMU模拟器

**Comment by cedar-c** [comment]
> 为什么我的连答题都还没过去啊...连文字都无法输入，而且挑战答题一直答个没完了... 
> win10 + MUMU模拟器

哈哈，你比我可怜，但是挑战答题默认是30题，所以时间肯定长，另外文字不能输入，你是不是没有装那个输入法，adbkey好像是，模拟器装上就可以了，我就是这样弄好的

**Comment by kessil** [comment]
> 
> 
> 答题耗时 447.82 秒
> 视听学习中...
> Traceback (most recent call last):
> File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\Program Files\AutoXue-master\xuexi__main__.py", line 41, in app.start(args.article, args.video, args.daily, args.challenge) File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 67, in start
> self._vdo_run() File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 52, in _vdo_run
> vd.run(count, delay)
> File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 74, in run
> self.enter()
> File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 48, in enter
> self.ad.tap(suggest) # 点击刷新
> File "D:\Program Files\AutoXue-master\xuexi\common\adble.py", line 147, in tap
> dx, dy = int(x.real), int(x.imag)
> AttributeError: 'list' object has no attribute 'real'
> 断开模拟器127.0.0.1:7555 成功
> 请按任意键继续. . .

不知为什么你的百灵推荐页点不了，确定有这个页吗？

**Comment by kessil** [comment]
挑战答题可以自己调节答多少题，使用前请先看README！遇到问题再看一遍README！OK？

**Comment by cedar-c** [comment]
> > 答题耗时 447.82 秒
> > 视听学习中...
> > Traceback (most recent call last):
> > File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\Program Files\AutoXue-master\xuexi__main__.py", line 41, in app.start(args.article, args.video, args.daily, args.challenge) File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 67, in start
> > self._vdo_run() File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 52, in _vdo_run
> > vd.run(count, delay)
> > File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 74, in run
> > self.enter()
> > File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 48, in enter
> > self.ad.tap(suggest) # 点击刷新
> > File "D:\Program Files\AutoXue-master\xuexi\common\adble.py", line 147, in tap
> > dx, dy = int(x.real), int(x.imag)
> > AttributeError: 'list' object has no attribute 'real'
> > 断开模拟器127.0.0.1:7555 成功
> > 请按任意键继续. . .
> 
> 不知为什么你的百灵推荐页点不了，确定有这个页吗？

我版本和大佬的测试版本一样，有百灵还是会出现错误，而且好像出错后再打开直接出错，删了重新下载打开才会先答题再出错，另外大佬能不能加一个检测是否答过题？我重复打开想测试视听是否有用都要等答完题

**Comment by dayyear** [comment]
我也遇到同样的问题，更新App版本到v2.5.0就可以了。

**Comment by PerhapSC** [comment]
> 挑战答题可以自己调节答多少题，使用前请先看README！遇到问题再看一遍README！OK？

感谢大佬！！！我多看看，请大佬息怒！！！

**Comment by PerhapSC** [comment]
> > 为什么我的连答题都还没过去啊...连文字都无法输入，而且挑战答题一直答个没完了...
> > win10 + MUMU模拟器
> 
> 哈哈，你比我可怜，但是挑战答题默认是30题，所以时间肯定长，另外文字不能输入，你是不是没有装那个输入法，adbkey好像是，模拟器装上就可以了，我就是这样弄好的

感谢楼下的朋友，是要更新到2.5，模拟器应用市场里最新的版本不是2.5.0，
另外悄悄问一下，在哪里修改挑战答题数目为10题啊，default还是custom..我每找到...
谢谢！

**Comment by PerhapSC** [comment]
> 我也遇到同样的问题，更新App版本到v2.5.0就可以了。

可以了！感谢您！

**Comment by PerhapSC** [comment]
> > 为什么我的连答题都还没过去啊...连文字都无法输入，而且挑战答题一直答个没完了...
> > win10 + MUMU模拟器
> 
> 哈哈，你比我可怜，但是挑战答题默认是30题，所以时间肯定长，另外文字不能输入，你是不是没有装那个输入法，adbkey好像是，模拟器装上就可以了，我就是这样弄好的

解决了，感动！

**Comment by kessil** [comment]
> 
> 
> > > 答题耗时 447.82 秒
> > > 视听学习中...
> > > Traceback (most recent call last):
> > > File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\Program Files\AutoXue-master\xuexi__main__.py", line 41, in app.start(args.article, args.video, args.daily, args.challenge) File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 67, in start
> > > self._vdo_run() File "D:\Program Files\AutoXue-master\xuexi__init__.py", line 52, in _vdo_run
> > > vd.run(count, delay)
> > > File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 74, in run
> > > self.enter()
> > > File "D:\Program Files\AutoXue-master\xuexi\media\viewer.py", line 48, in enter
> > > self.ad.tap(suggest) # 点击刷新
> > > File "D:\Program Files\AutoXue-master\xuexi\common\adble.py", line 147, in tap
> > > dx, dy = int(x.real), int(x.imag)
> > > AttributeError: 'list' object has no attribute 'real'
> > > 断开模拟器127.0.0.1:7555 成功
> > > 请按任意键继续. . .
> > 
> > 
> > 不知为什么你的百灵推荐页点不了，确定有这个页吗？
> 
> 我版本和大佬的测试版本一样，可以用了，但是好像出错后再打开直接出错，删了重新下载打开才会先答题再出错，另外大佬能不能加一个检测是否答过题？答过直接跳视听？

你提的这个检测功能不会考虑增加，因为脚本根本就不在乎是否答过题或是什么，它只要按部就班做好自己的事就可以了
但是我可以给你提供两个思路：
1. README说过，运行脚本可以提供四个参数[-a][-c][-d][-v]，这四个参数就是执行四大操作的开关，可以根据需要自己指定
2. README还说过，可以单独执行某个功能
> 形如 python -m xuexi.media.viewer -v
## 任何个性化的需求请将命令行参数和配置文件搭配食用，更美味哦

**Comment by cedar-c** [comment]
> > > 为什么我的连答题都还没过去啊...连文字都无法输入，而且挑战答题一直答个没完了... 
> > > win10 + MUMU模拟器
> > 
> > 
> > 哈哈，你比我可怜，但是挑战答题默认是30题，所以时间肯定长，另外文字不能输入，你是不是没有装那个输入法，adbkey好像是，模拟器装上就可以了，我就是这样弄好的
> 
> 感谢楼下的朋友，是要更新到2.5，模拟器应用市场里最新的版本不是2.5.0，
> 另外悄悄问一下，在哪里修改挑战答题数目为10题啊，默认还是定制..我每找到。 .. 
> 谢谢！

在config-custom.ini里面改challenge_count = 30，30就是挑战答题的数目，改成challenge_count = 10就好了
