### ISSUE TITLE
新版，答题可以用，试听就错误了，求助

### ISSUE THREAD

**Issue by cedar-c** [kessil/AutoXue#41]
视听学习中...
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "F:\AutoXue-master\xuexi\__init__.py", line 67, in start
    self._vdo_run()
  File "F:\AutoXue-master\xuexi\__init__.py", line 52, in _vdo_run
    vd.run(count, delay)
  File "F:\AutoXue-master\xuexi\media\viewer.py", line 74, in run
    self.enter()
  File "F:\AutoXue-master\xuexi\media\viewer.py", line 48, in enter
    self.ad.tap(suggest) # 点击刷新
  File "F:\AutoXue-master\xuexi\common\adble.py", line 147, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功

在初次安装的时候最后提示这个：
You are using pip version 9.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
按照提示更新的再点还是这样......

另外因为本身有其他模拟器，就想改端口，在common/adble.py中改了不管用怎么回事？

**Comment by kessil** [comment]
pip版本告警不影响，忽略即可
改adb端口请看./xuexi/config-default.ini第53行，请在config-custom.ini中按如下改：
```
; ./xuexi/config-custom.ini
[mumu]
port=你的端口
```

**Comment by cedar-c** [comment]
> pip版本告警不影响，忽略即可
> 改adb端口请看./xuexi/config-default.ini第53行，请在config-custom.ini中按如下改：
> 
> ```
> ; ./xuexi/config-custom.ini
> [mumu]
> port=你的端口
> ```

不好意思，这个端口没看懂怎么加，在custom里面哪个位置？没看懂。。。

**Comment by cedar-c** [comment]
> > pip版本告警不影响，忽略即可
> > 改adb端口请看./xuexi/config-default.ini第53行，请在config-custom.ini中按如下改：
> > ```
> > ; ./xuexi/config-custom.ini
> > [mumu]
> > port=你的端口
> > ```
> 
> 不好意思，这个端口没看懂怎么加，在custom里面哪个位置？没看懂。。。
