### ISSUE TITLE
答题只要出现输入的题目出错误提示,如何解决,非常感谢您的作品

### ISSUE THREAD

**Issue by lubei1983** [kessil/AutoXue#45]
自动提交答案: 调查研究下基层
Traceback (most recent call last):
  File "C:\Users\swlys\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\swlys\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\AutoXue-master\xuexi\__init__.py", line 62, in start
    self._quiz_run(day, chg)
  File "D:\AutoXue-master\xuexi\__init__.py", line 57, in _quiz_run
    qApp.start(day, chg)
  File "D:\AutoXue-master\xuexi\quiz\__init__.py", line 72, in start
    self._run_daily()
  File "D:\AutoXue-master\xuexi\quiz\__init__.py", line 38, in _run_daily
    dq.run(round, count)
  File "D:\AutoXue-master\xuexi\quiz\daily.py", line 266, in run
    self._dispatch()
  File "D:\AutoXue-master\xuexi\quiz\daily.py", line 247, in _dispatch
    self._submit() # 点击确定
  File "D:\AutoXue-master\xuexi\quiz\daily.py", line 133, in _submit
    self.ad.tap(self.p_submit)
  File "D:\AutoXue-master\xuexi\common\adble.py", line 147, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by kessil** [comment]
这个问题就是‘确定’按钮的坐标没解析到，你是什么设备，上传xml看看

**Comment by lubei1983** [comment]
已经解决问题了,是没有在模拟器安装adb.apk 非常感谢您的作品

**Comment by lubei1983** [comment]
> 这个问题就是‘确定’按钮的坐标没解析到，你是什么设备，上传xml看看

提一个不成熟的小建议,能否在开始积分这个bat里,做成1视听文章阅读学习 2答题 3分享订阅收藏发表观点 4全自动完成所有项目 以免因为用户中断以及模拟器出bug之类的问题造成的重复做项目
