### ISSUE TITLE
新闻学习中出错了

### ISSUE THREAD

**Issue by xiao3783** [kessil/AutoXue#51]
我的也是新闻学习中。。然后出错了
视听学习完成，返回首页
观影耗时 1144.08 秒
新闻学习中...
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi\__main__.py", line 41,
in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi\__init__.py", line 72,
in start
    self._art_run()
  File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi\__init__.py", line 44,
in _art_run
    rd.run(count, delay, ssc)
  File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi\media\reader.py", line
200, in run
    self.ad.slide(complex(self.fixed.real, article[1].imag), self.fixed, duratio
n=1000)
AttributeError: 'list' object has no attribute 'real'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. .

**Comment by xiao3783** [comment]
> 我的也是新闻学习中。。然后出错了
> 视听学习完成，返回首页
> 观影耗时 1144.08 秒
> 新闻学习中...
> Traceback (most recent call last):
> File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_mai n "**main**", mod_spec) File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi__main__.py", line 41, in app.start(args.article, args.video, args.daily, args.challenge) File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi__init__.py", line 72,
> in start
> self._art_run() File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi__init__.py", line 44,
> in _art_run
> rd.run(count, delay, ssc)
> File "C:\Users\Administrator\Desktop\AutoXue-2.2\xuexi\media\reader.py", line
> 200, in run
> self.ad.slide(complex(self.fixed.real, article[1].imag), self.fixed, duratio
> n=1000)
> AttributeError: 'list' object has no attribute 'real'
> 断开模拟器127.0.0.1:7555 成功
> 请按任意键继续. .

[uimumu.txt](https://github.com/kessil/AutoXue/files/3500557/uimumu.txt)

**Comment by rxgit1** [comment]
我的也是

**Comment by SoftPaper** [comment]
新闻：第 17 则已阅，耗时 43.38 秒
Traceback (most recent call last):
  File "C:\Users\FengChao\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\FengChao\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Install\AutoXue\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\Install\AutoXue\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "D:\Install\AutoXue\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "D:\Install\AutoXue\xuexi\media\reader.py", line 173, in run
    articles = [(t, p) for t, p in zip(self.xm.texts(cfg.get(self.rules, 'rule_news_content')), self.xm.pos(cfg.get(self.rules, 'rule_news_bounds')))]
TypeError: zip argument #2 must support iteration
断开模拟器127.0.0.1:7555 成功
