### ISSUE TITLE
点击开始几份不能正常运行

### ISSUE THREAD

**Issue by zsdw52** [kessil/AutoXue#55]
Traceback (most recent call last):
  File "D:\Program Files\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Program Files\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\Program Files\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Administrator\Desktop\AutoXue-master\xuexi\__init__.py", line 25, in <module>
    cfg.read(path/'config-custom.ini', encoding='utf-8')
  File "D:\Program Files\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "D:\Program Files\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: WindowsPath('C:/Users/Administrator/Desktop/AutoXue-master/xuexi/config-custom.ini'), line: 1
'\ufeff[common]\n'
请按任意键继续. . .

**Comment by zsdw52** [comment]
点开始运行以后就这样显示了，然后模拟器也没有任何反应，请问如何解决啊，谢谢。

**Comment by kessil** [comment]
动过custom.ini？用的系统自带记事本？你的custom.ini配置缺少section？

**Comment by zsdw52** [comment]
是的，用系统自带笔记本打开的，难道不是这样吗？

**Comment by zsdw52** [comment]
额，那用什么...谢谢

**Comment by kessil** [comment]
> 
> 
> 额，那用什么...谢谢

我回复里面给的是廖雪峰大神的解释，廖大推荐了两款编辑器Sublime Text和Notepad++，这两款都很好用，我再给你推荐一款编辑器，也是微软自家的，vscode，也很好用，自己选择吧。
