### ISSUE TITLE
文章学习出错请如何解决

### ISSUE THREAD

**Issue by LIUYUYANSZ** [kessil/AutoXue#58]
新闻学习中...
[24] 部分银行退出理财产品发行市场——区域银行理财资源集中度提升...
新闻：第 24 则已阅，耗时 39.01 秒
数据库添加成功！ 部分银行退出理财产品发行市场——区域银行理财资源集中度提升
[23] 加快“僵尸企业”出清...
新闻：第 23 则已阅，耗时 38.84 秒
数据库添加成功！ 加快“僵尸企业”出清
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\学习脚本\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\学习脚本\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "D:\学习脚本\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "D:\学习脚本\xuexi\media\reader.py", line 227, in run
    if pos_bottom.imag > self.fixed_bottom.imag:
AttributeError: 'list' object has no attribute 'imag'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by ohhhyy** [comment]
同出错，不知道为什么，存放路径不能有中文么？


新闻学习中...
Traceback (most recent call last):
  File "C:\Users\hyyyy\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hyyyy\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi\media\reader.py", line 227, in run
    if pos_bottom.imag > self.fixed_bottom.imag:
AttributeError: 'list' object has no attribute 'imag'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by ohhhyy** [comment]
xml文件是这个
[uimumu.xml.txt](https://github.com/kessil/AutoXue/files/3507949/uimumu.xml.txt)
