### ISSUE TITLE
文章学习出错，XML附件，求解决谢谢

### ISSUE THREAD

**Issue by ohhhyy** [kessil/AutoXue#59]
新闻学习中...
Traceback (most recent call last):
File "C:\Users\hyyyy\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "C:\Users\hyyyy\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi_main.py", line 41, in 
app.start(args.article, args.video, args.daily, args.challenge)
File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi_init.py", line 72, in start
self.art_run()
File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi_init.py", line 44, in _art_run
rd.run(count, delay, ssc)
File "C:\Users\hyyyy\Desktop\未归类\学习强国\学习强国 41分\AutoXue-master\xuexi\media\reader.py", line 227, in run
if pos_bottom.imag > self.fixed_bottom.imag:
AttributeError: 'list' object has no attribute 'imag'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

[uimumu.xml.txt](https://github.com/kessil/AutoXue/files/3507955/uimumu.xml.txt)

**Comment by kessil** [comment]
您还没有订阅内容

**Comment by ohhhyy** [comment]
原来是新号的问题。。谢谢解决
