### ISSUE TITLE
最新版本怎么卸载干净呢

### ISSUE THREAD

**Issue by nqsd123** [kessil/AutoXue#61]
1.0使用正常,安装2.0以后都无法用了,想用回1.0,请问怎么把2.0清理干净

**Comment by kessil** [comment]
无法用的理由呢，退到branch 20190808分支有1.0

**Comment by nqsd123** [comment]
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: device not found
error: device not found
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    run(session,842)
  File "main.py", line 50, in run
    pull_xml(filename)
  File "G:\学习强国\venv\Scripts\adble.py", line 23, in pull_xml
    if os.path.getsize(filename):
  File "H:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\generi
cpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'G:\\学习强国\\venv\\Scr
ipts\\ui.xml'
出现这个错误。请大神帮忙看下
