### ISSUE TITLE
大神我看到你特意更新换了夜神端口非常感谢

### ISSUE THREAD

**Issue by lmaisui** [kessil/AutoXue#63]
我也学会了如何更换端口,链接一切正常 但是我发现运行时候报错 : 不是可点击坐标,是不是说明一个问题 根本不支持夜神模拟器!  用会木木确实正常 但是木木模拟器真的好难用

**Comment by kessil** [comment]
没有问题，正常使用，xpath都改过了

**Comment by lmaisui** [comment]
> 没有问题，正常使用，xpath都改过了

已经修改过了吗   那我在测试一下 不知道哪里的问题

**Comment by lmaisui** [comment]
> > 没有问题，正常使用，xpath都改过了
> 
> 已经修改过了吗 那我在测试一下 不知道哪里的问题

* daemon started successfully
当前设备 127.0.0.1:62001
Traceback (most recent call last):
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\common\adble.py", line 167, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86150\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\86150\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\__init__.py", line 62, in start
    self._quiz_run(day, chg)
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\__init__.py", line 57, in _quiz_run
    qApp.start(day, chg)
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\quiz\__init__.py", line 65, in start
    self.ad.tap(pos)
  File "C:\Users\86150\Desktop\学习\AutoXue-master\xuexi\common\adble.py", line 169, in tap
    raise AttributeError(f'{x} 不是可点击的坐标')
AttributeError: [] 不是可点击的坐标
断开模拟器127.0.0.1:62001 成功

大佬 我今天特意换了一台电脑 还是出这个问题
