### ISSUE TITLE
学习文章出错 评论报错

### ISSUE THREAD

**Issue by a596544022** [kessil/AutoXue#64]
[24] 【在习近平新时代中国特色社会主义思想指引下——新时代 新作为 新篇章】脱贫攻坚战进入决胜关键阶段 我国着力解决“两不愁三保障”突出问题...
分享一篇文章!
留言一篇文章: 老百姓对生活美好的向往是我们的目标
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\demo\AutoXue\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\demo\AutoXue\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "D:\demo\AutoXue\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "D:\demo\AutoXue\xuexi\media\reader.py", line 246, in run
    ssc -= self._star_share_comment(title)
  File "D:\demo\AutoXue\xuexi\media\reader.py", line 163, in _star_share_comment
    offset = offset_dict[max(self.ad.wmsize)]
KeyError: 1440
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .

**Comment by kessil** [comment]
分辨率问题

**Comment by fzhqzxguest** [comment]
@kessil    以下什么问题。

当前设备 emulator-5554
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\adb\AutoXue-master\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "C:\adb\AutoXue-master\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "C:\adb\AutoXue-master\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "C:\adb\AutoXue-master\AutoXue-master\xuexi\media\reader.py", line 223, in run
    self.enter()
  File "C:\adb\AutoXue-master\AutoXue-master\xuexi\media\reader.py", line 81, in enter
    p0, p1 = columns[0][1], columns[-1][1]
IndexError: list index out of range
断开模拟器127.0.0.1:5555 成功
请按任意键继续. . .

**Comment by ohhhyy** [comment]
分辨率改成1024x576或者864x486

**Comment by cedar-c** [comment]
> @kessil 以下什么问题。（用新手机号，雷电模拟器，学习强国文章学习已订阅，其他视听学习等可以）
> 
> 当前设备 emulator-5554
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\adb\AutoXue-master\AutoXue-master\xuexi__main__.py", line 41, in app.start(args.article, args.video, args.daily, args.challenge) File "C:\adb\AutoXue-master\AutoXue-master\xuexi__init__.py", line 72, in start
> self._art_run() File "C:\adb\AutoXue-master\AutoXue-master\xuexi__init__.py", line 44, in _art_run
> rd.run(count, delay, ssc)
> File "C:\adb\AutoXue-master\AutoXue-master\xuexi\media\reader.py", line 223, in run
> self.enter()
> File "C:\adb\AutoXue-master\AutoXue-master\xuexi\media\reader.py", line 81, in enter
> p0, p1 = columns[0][1], columns[-1][1]
> IndexError: list index out of range
> 断开模拟器127.0.0.1:5555 成功
> 请按任意键继续. . .

兄弟，你雷电是 怎么能用的？为什么我的不行

**Comment by fzhqzxguest** [comment]
@cedar-c   ,以下是config-custom.ini配置单，要把device = nox，port = 7555 改成device = mumu，port = 5555


[common]
; 设备名称 指明连接的安卓设备, 需要同名[section]
device = mumu

; 数据库URI
; 目前仅使用database_uri， 另两个是担心以后每日答题和挑战答题出现同一题造成bug，只要将三个配置成一样即可
database_uri = sqlite:///./xuexi/data-dev.sqlite
database_daily = sqlite:///./xuexi/data-dev.sqlite
database_challenge = sqlite:///./xuexi/data-dev.sqlite
; 已阅文章清单
database_article = sqlite:///./xuexi/data-article.sqlite

; 是否用户,标记是否保存新题副本
is_user = false

; 答题题库临时存放路径，根据is_user决定
daily_json = ./xuexi/src/json/daily.json
challenge_json = ./xuexi/src/json/challenge.json

; 评论池
comments_json = ./xuexi/src/json/comments.json

; 每日答题永不停
daily_forver = false

; 每日答题每组时间间隔 之前有发生过10秒内开始下一组不得分的情况，后来又没了，所以把这个时间间隔写活
daily_delay = 3
; 挑战答题题数， 积分设为10+， 积点点通设为30+
challenge_count = 30
# 挑战答题时延， 设0-5， 0表示随机
challenge_delay = 1
; 视听学习视频数量， 积分设为6+，积点点通设为20+ 相应地，确保video_count*video_delay>1080（18分钟）
video_count = 25 
; 视听学习每个视频观看秒数
video_delay = 60
; 是否启用文章清单
enable_article_list = false
; 阅读栏目,建议： 设置为订阅，关注公众号、取关公众平台（因为公众平台喜欢发视频，但咱们只想刷文章）
article_column_name = 订阅
; 阅读文章数量，， 积分设为6+，积点点通设为20+ 相应地，确保article_count*article_delay>720（12分钟）
article_count = 25
; 阅读文章秒数
article_delay = 30
; 收藏、分享、留言的文章篇数 积分设为2+， 该操作不积点点通
star_share_comment = 3
; ==============================================================================================================




; 针对留言发布按钮由于输入法栏导致的偏移量
[resolution]
864 = 17
1024 = 23
1280 = 26
2240 = 35




; mumu模拟器
[mumu]
; 设备类型是否为模拟器 true | false
is_virtual_machine = true
xml_uri = ./xuexi/src/xml/uimumu.xml
; host:port 指明连接的模拟器, 当is_virtual_machine = true 时有效
; 主机 host 默认127.0.0.1
; 端口 port 由模拟器决定
; MuMu模拟器 7555(windows) 5555(Mac)
; 夜神安卓模拟器 62001
; 逍遥安卓模拟器 21503
; 雷电安卓模拟器 5555
; 天天安卓模拟器 5037
; 安卓模拟器大师 54001
; Genymotion 5555
; BlueStacks 5555
host = 127.0.0.1
port = 5555

; rule前缀为xpath规则，pos前缀为坐标的复数形式
; ======================================兄弟节点、父节点示例======================================================
; 获取第三个node标签的下一个node标签："//node[@id='3']/following-sibling::node[1]"
; 获取第三个node标签后面的第N个标签："//node[@id='3']/following-sibling::*[N]"
; 获取第三个node标签的上一个node标签："//node[@id='3']/preceding-sibling::node[1]"
; 获取第三个node标签的前面的第N个标签："//node[@id='3']/preceding-sibling::*[N]"
; 获取第三个node标签的父标签："//node[@id=='3']/.."
; ==============================================================================================================
; 首页Bottom栏xpath规则
; 强国通 | 百灵 | 学习 | 视听 | 我的
rule_bottom_message = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_message"]/@bounds
rule_bottom_ding = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_ding"]/@bounds
rule_bottom_work = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_work"]/@bounds
rule_bottom_contact = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_contact"]/@bounds
rule_bottom_mine = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_mine"]/@bounds
; 我要答题xpath规则
; 我要答题入口，[我要答题]按钮
rule_quiz_entry = //node[@content-desc="我要答题"]/@bounds
; 我要答题出口：[<]左上角后退按钮 我要答题父节点的第一个子节点,答题记录的前一个兄弟节点
rule_quiz_exit = //node[@content-desc="答题记录"]/preceding-sibling::node[1]/@bounds
; 每日答题入口 [每日答题]按钮
rule_daily_entry = //node[@content-desc="每日答题"]/@bounds
; 挑战答题入口　[挑战答题]按钮
rule_challenge_entry = //node[@content-desc="挑战答题"]/@bounds
; ---------------------------------------------------------------------------------------------------------------
; 每日答题xpath规则
; 题型：填空题、单选题、多选题
rule_type = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/preceding-sibling::node[1]/@content-desc
; 题干
rule_content = //node[@class="android.widget.ListView"]/../node[@index="2"]/@content-desc
rule_blank_content = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/following-sibling::node[1]/node[@class="android.view.View"]/@content-desc
; 选项坐标
rule_options = //node[@class="android.widget.ListView"]/node/@bounds
; 填空题输入框坐标
rule_edits = //node[@class="android.widget.EditText"]/following-sibling::node[1]/@bounds
; 分数
rule_score = //node[@content-desc="积分： "]/following-sibling::node[1]/@content-desc
rule_score_reached = //node[@content-desc="领取奖励已达今日上限"]/@content-desc
; 正确答案， node[答案解析]的下一个标签
rule_desc = //node[@content-desc="答案解析"]/following-sibling::node[1]/@content-desc
rule_note = //node[@content-desc="答案解析"]/following-sibling::node[2]/@content-desc

; 按钮坐标 [<]左上角返回按钮、[确定、下一题、完成]右上角提交按钮、答题报告中返回按钮、答题报告中再来一组按钮
rule_back = //node[@class="android.widget.Button"]/../preceding-sibling::node[1]/@bounds
rule_submit = //node[@class="android.widget.Button"]/@bounds
rule_return = //node[@content-desc="返回"]/@bounds
rule_next = //node[@content-desc="再来一组"]/@bounds
; ==============================================================================================================
; 挑战答题xpath规则
; 题型：挑战题
; 题干
rule_challenge_content = //node[@class="android.widget.ListView"]/preceding-sibling::node[1]/@content-desc
; 选项内容
rule_challenge_options_content = //node[@class="android.widget.ListView"]/node//node[@index="1" and @class="android.view.View"]/@content-desc
; 选项坐标
rule_challenge_options_bounds =  //node[@class="android.widget.ListView"]/node/@bounds
; 复活按钮和再来一局按钮坐标
rule_judge_bounds = //node[@content-desc="分享就能复活" or @content-desc="再来一局"]/@bounds
rule_revive_bounds = //node[@content-desc="分享就能复活"]/@bounds
rule_again_bounds = //node[@content-desc="再来一局"]/@bounds
; rule_close_bounds = //node[@content-desc="结束本局"]/bounds
; ==============================================================================================================

; 视听学习xpath规则
; 百灵第一个视频
rule_first_video = //node[@class="android.widget.ListView"]/node[1]/@bounds

; 阅读文章xpath规则
rule_columns_content = //node[@class="android.view.ViewGroup"]/node[@class="android.widget.LinearLayout"]/node[@class="android.widget.TextView"]/@text
rule_columns_bounds = //node[@class="android.view.ViewGroup"]/node[@class="android.widget.LinearLayout"]/@bounds
rule_fixed_top_bounds = ////node[@class="android.widget.ListView"]/node[1]/@bounds
rule_fixed_bottom_bounds = ////node[@class="android.widget.ListView"]/node[last()]/@bounds
rule_news_bounds = //node[@class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@bounds
rule_news_content = //node[@class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@text
rule_news3pic_bounds = ////node[@class="android.widget.ListView"]/node/node[@class="android.widget.LinearLayout" and @index="0"]/node[@class="android.widget.TextView"]/@bounds
rule_news3pic_content = ////node[@class="android.widget.ListView"]/node/node[@class="android.widget.LinearLayout" and @index="0"]/node[@class="android.widget.TextView"]/@text
rule_star_bounds = //node[@text="欢迎发表你的观点"]/../node[3]/@bounds
rule_share_bounds = //node[@text="欢迎发表你的观点"]/../node[4]/@bounds
rule_comment_bounds = //node[@text="欢迎发表你的观点"]/@bounds
rule_share2xuexi_bounds = //node[@text="分享到学习强国"]/@bounds
rule_publish_bounds = //node[@text="发布"]/@bounds

**Comment by cedar-c** [comment]
> @cedar-c ,以下是config-custom.ini配置单，要把device = nox，port = 7555 改成device = mumu，port = 5555
> 
> [common]
> ; 设备名称 指明连接的安卓设备, 需要同名[section]
> device = mumu
> 
> ; 数据库URI
> ; 目前仅使用database_uri， 另两个是担心以后每日答题和挑战答题出现同一题造成bug，只要将三个配置成一样即可
> database_uri = sqlite:///./xuexi/data-dev.sqlite
> database_daily = sqlite:///./xuexi/data-dev.sqlite
> database_challenge = sqlite:///./xuexi/data-dev.sqlite
> ; 已阅文章清单
> database_article = sqlite:///./xuexi/data-article.sqlite
> 
> ; 是否用户,标记是否保存新题副本
> is_user = false
> 
> ; 答题题库临时存放路径，根据is_user决定
> daily_json = ./xuexi/src/json/daily.json
> challenge_json = ./xuexi/src/json/challenge.json
> 
> ; 评论池
> comments_json = ./xuexi/src/json/comments.json
> 
> ; 每日答题永不停
> daily_forver = false
> 
> ; 每日答题每组时间间隔 之前有发生过10秒内开始下一组不得分的情况，后来又没了，所以把这个时间间隔写活
> daily_delay = 3
> ; 挑战答题题数， 积分设为10+， 积点点通设为30+
> challenge_count = 30
> 
> # 挑战答题时延， 设0-5， 0表示随机
> challenge_delay = 1
> ; 视听学习视频数量， 积分设为6+，积点点通设为20+ 相应地，确保video_count_video_delay>1080（18分钟） video_count = 25 ; 视听学习每个视频观看秒数 video_delay = 60 ; 是否启用文章清单 enable_article_list = false ; 阅读栏目,建议： 设置为订阅，关注公众号、取关公众平台（因为公众平台喜欢发视频，但咱们只想刷文章） article_column_name = 订阅 ; 阅读文章数量，， 积分设为6+，积点点通设为20+ 相应地，确保article_count_article_delay>720（12分钟）
> article_count = 25
> ; 阅读文章秒数
> article_delay = 30
> ; 收藏、分享、留言的文章篇数 积分设为2+， 该操作不积点点通
> star_share_comment = 3
> ; ==============================================================================================================
> 
> ; 针对留言发布按钮由于输入法栏导致的偏移量
> [resolution]
> 864 = 17
> 1024 = 23
> 1280 = 26
> 2240 = 35
> 
> ; mumu模拟器
> [mumu]
> ; 设备类型是否为模拟器 true | false
> is_virtual_machine = true
> xml_uri = ./xuexi/src/xml/uimumu.xml
> ; host:port 指明连接的模拟器, 当is_virtual_machine = true 时有效
> ; 主机 host 默认127.0.0.1
> ; 端口 port 由模拟器决定
> ; MuMu模拟器 7555(windows) 5555(Mac)
> ; 夜神安卓模拟器 62001
> ; 逍遥安卓模拟器 21503
> ; 雷电安卓模拟器 5555
> ; 天天安卓模拟器 5037
> ; 安卓模拟器大师 54001
> ; Genymotion 5555
> ; BlueStacks 5555
> host = 127.0.0.1
> port = 5555
> 
> ; rule前缀为xpath规则，pos前缀为坐标的复数形式
> ; ======================================兄弟节点、父节点示例======================================================
> ; 获取第三个node标签的下一个node标签："//node[@id='3']/following-sibling::node[1]"
> ; 获取第三个node标签后面的第N个标签："//node[@id='3']/following-sibling::_[N]" ; 获取第三个node标签的上一个node标签："//node[@id='3']/preceding-sibling::node[1]" ; 获取第三个node标签的前面的第N个标签："//node[@id='3']/preceding-sibling::_[N]"
> ; 获取第三个node标签的父标签："//node[@id=='3']/.."
> ; ==============================================================================================================
> ; 首页Bottom栏xpath规则
> ; 强国通 | 百灵 | 学习 | 视听 | 我的
> rule_bottom_message = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_message"]/@bounds
> rule_bottom_ding = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_ding"]/@bounds
> rule_bottom_work = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_work"]/@bounds
> rule_bottom_contact = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_contact"]/@bounds
> rule_bottom_mine = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_mine"]/@bounds
> ; 我要答题xpath规则
> ; 我要答题入口，[我要答题]按钮
> rule_quiz_entry = //node[@content-desc="我要答题"]/@bounds
> ; 我要答题出口：[<]左上角后退按钮 我要答题父节点的第一个子节点,答题记录的前一个兄弟节点
> rule_quiz_exit = //node[@content-desc="答题记录"]/preceding-sibling::node[1]/@bounds
> ; 每日答题入口 [每日答题]按钮
> rule_daily_entry = //node[@content-desc="每日答题"]/@bounds
> ; 挑战答题入口　[挑战答题]按钮
> rule_challenge_entry = //node[@content-desc="挑战答题"]/@bounds
> ; ---------------------------------------------------------------------------------------------------------------
> ; 每日答题xpath规则
> ; 题型：填空题、单选题、多选题
> rule_type = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/preceding-sibling::node[1]/@content-desc
> ; 题干
> rule_content = //node[@Class="android.widget.ListView"]/../node[@index="2"]/@content-desc
> rule_blank_content = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/following-sibling::node[1]/node[@Class="android.view.View"]/@content-desc
> ; 选项坐标
> rule_options = //node[@Class="android.widget.ListView"]/node/@bounds
> ; 填空题输入框坐标
> rule_edits = //node[@Class="android.widget.EditText"]/following-sibling::node[1]/@bounds
> ; 分数
> rule_score = //node[@content-desc="积分： "]/following-sibling::node[1]/@content-desc
> rule_score_reached = //node[@content-desc="领取奖励已达今日上限"]/@content-desc
> ; 正确答案， node[答案解析]的下一个标签
> rule_desc = //node[@content-desc="答案解析"]/following-sibling::node[1]/@content-desc
> rule_note = //node[@content-desc="答案解析"]/following-sibling::node[2]/@content-desc
> 
> ; 按钮坐标 [<]左上角返回按钮、[确定、下一题、完成]右上角提交按钮、答题报告中返回按钮、答题报告中再来一组按钮
> rule_back = //node[@Class="android.widget.Button"]/../preceding-sibling::node[1]/@bounds
> rule_submit = //node[@Class="android.widget.Button"]/@bounds
> rule_return = //node[@content-desc="返回"]/@bounds
> rule_next = //node[@content-desc="再来一组"]/@bounds
> ; ==============================================================================================================
> ; 挑战答题xpath规则
> ; 题型：挑战题
> ; 题干
> rule_challenge_content = //node[@Class="android.widget.ListView"]/preceding-sibling::node[1]/@content-desc
> ; 选项内容
> rule_challenge_options_content = //node[@Class="android.widget.ListView"]/node//node[@index="1" and @Class="android.view.View"]/@content-desc
> ; 选项坐标
> rule_challenge_options_bounds = //node[@Class="android.widget.ListView"]/node/@bounds
> ; 复活按钮和再来一局按钮坐标
> rule_judge_bounds = //node[@content-desc="分享就能复活" or @content-desc="再来一局"]/@bounds
> rule_revive_bounds = //node[@content-desc="分享就能复活"]/@bounds
> rule_again_bounds = //node[@content-desc="再来一局"]/@bounds
> ; rule_close_bounds = //node[@content-desc="结束本局"]/bounds
> ; ==============================================================================================================
> 
> ; 视听学习xpath规则
> ; 百灵第一个视频
> rule_first_video = //node[@Class="android.widget.ListView"]/node[1]/@bounds
> 
> ; 阅读文章xpath规则
> rule_columns_content = //node[@Class="android.view.ViewGroup"]/node[@Class="android.widget.LinearLayout"]/node[@Class="android.widget.TextView"]/@text
> rule_columns_bounds = //node[@Class="android.view.ViewGroup"]/node[@Class="android.widget.LinearLayout"]/@bounds
> rule_fixed_top_bounds = ////node[@Class="android.widget.ListView"]/node[1]/@bounds
> rule_fixed_bottom_bounds = ////node[@Class="android.widget.ListView"]/node[last()]/@bounds
> rule_news_bounds = //node[@Class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@bounds
> rule_news_content = //node[@Class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@text
> rule_news3pic_bounds = ////node[@Class="android.widget.ListView"]/node/node[@Class="android.widget.LinearLayout" and @index="0"]/node[@Class="android.widget.TextView"]/@bounds
> rule_news3pic_content = ////node[@Class="android.widget.ListView"]/node/node[@Class="android.widget.LinearLayout" and @index="0"]/node[@Class="android.widget.TextView"]/@text
> rule_star_bounds = //node[@text="欢迎发表你的观点"]/../node[3]/@bounds
> rule_share_bounds = //node[@text="欢迎发表你的观点"]/../node[4]/@bounds
> rule_comment_bounds = //node[@text="欢迎发表你的观点"]/@bounds
> rule_share2xuexi_bounds = //node[@text="分享到学习强国"]/@bounds
> rule_publish_bounds = //node[@text="发布"]/@bounds

大神更新了，雷电确实可以连接了，但是好像布局不太一样？我刚连上就报错坐标什么的，正在学着改，不知道大神会不会好心把雷电也给更新了添上去。

**Comment by cedar-c** [comment]
参照楼上大兄弟的确实可以连接了，但是不知道为什么连上就报错，试过改分辨率也不管用
Traceback (most recent call last):
  File "F:\AutoXue-master\xuexi\common\adble.py", line 167, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "F:\AutoXue-master\xuexi\__init__.py", line 62, in start
    self._quiz_run(day, chg)
  File "F:\AutoXue-master\xuexi\__init__.py", line 57, in _quiz_run
    qApp.start(day, chg)
  File "F:\AutoXue-master\xuexi\quiz\__init__.py", line 65, in start
    self.ad.tap(pos)
  File "F:\AutoXue-master\xuexi\common\adble.py", line 169, in tap
    raise AttributeError(f'{x} 不是可点击的坐标')
AttributeError: [] 不是可点击的坐标

[uileidian.xml.txt](https://github.com/kessil/AutoXue/files/3515148/uileidian.xml.txt)

**Comment by cedar-c** [comment]
> @cedar-c ,以下是config-custom.ini配置单，要把device = nox，port = 7555 改成device = mumu，port = 5555
> 
> [common]
> ; 设备名称 指明连接的安卓设备, 需要同名[section]
> device = mumu
> 
> ; 数据库URI
> ; 目前仅使用database_uri， 另两个是担心以后每日答题和挑战答题出现同一题造成bug，只要将三个配置成一样即可
> database_uri = sqlite:///./xuexi/data-dev.sqlite
> database_daily = sqlite:///./xuexi/data-dev.sqlite
> database_challenge = sqlite:///./xuexi/data-dev.sqlite
> ; 已阅文章清单
> database_article = sqlite:///./xuexi/data-article.sqlite
> 
> ; 是否用户,标记是否保存新题副本
> is_user = false
> 
> ; 答题题库临时存放路径，根据is_user决定
> daily_json = ./xuexi/src/json/daily.json
> challenge_json = ./xuexi/src/json/challenge.json
> 
> ; 评论池
> comments_json = ./xuexi/src/json/comments.json
> 
> ; 每日答题永不停
> daily_forver = false
> 
> ; 每日答题每组时间间隔 之前有发生过10秒内开始下一组不得分的情况，后来又没了，所以把这个时间间隔写活
> daily_delay = 3
> ; 挑战答题题数， 积分设为10+， 积点点通设为30+
> challenge_count = 30
> 
> # 挑战答题时延， 设0-5， 0表示随机
> challenge_delay = 1
> ; 视听学习视频数量， 积分设为6+，积点点通设为20+ 相应地，确保video_count_video_delay>1080（18分钟） video_count = 25 ; 视听学习每个视频观看秒数 video_delay = 60 ; 是否启用文章清单 enable_article_list = false ; 阅读栏目,建议： 设置为订阅，关注公众号、取关公众平台（因为公众平台喜欢发视频，但咱们只想刷文章） article_column_name = 订阅 ; 阅读文章数量，， 积分设为6+，积点点通设为20+ 相应地，确保article_count_article_delay>720（12分钟）
> article_count = 25
> ; 阅读文章秒数
> article_delay = 30
> ; 收藏、分享、留言的文章篇数 积分设为2+， 该操作不积点点通
> star_share_comment = 3
> ; ==============================================================================================================
> 
> ; 针对留言发布按钮由于输入法栏导致的偏移量
> [resolution]
> 864 = 17
> 1024 = 23
> 1280 = 26
> 2240 = 35
> 
> ; mumu模拟器
> [mumu]
> ; 设备类型是否为模拟器 true | false
> is_virtual_machine = true
> xml_uri = ./xuexi/src/xml/uimumu.xml
> ; host:port 指明连接的模拟器, 当is_virtual_machine = true 时有效
> ; 主机 host 默认127.0.0.1
> ; 端口 port 由模拟器决定
> ; MuMu模拟器 7555(windows) 5555(Mac)
> ; 夜神安卓模拟器 62001
> ; 逍遥安卓模拟器 21503
> ; 雷电安卓模拟器 5555
> ; 天天安卓模拟器 5037
> ; 安卓模拟器大师 54001
> ; Genymotion 5555
> ; BlueStacks 5555
> host = 127.0.0.1
> port = 5555
> 
> ; rule前缀为xpath规则，pos前缀为坐标的复数形式
> ; ======================================兄弟节点、父节点示例======================================================
> ; 获取第三个node标签的下一个node标签："//node[@id='3']/following-sibling::node[1]"
> ; 获取第三个node标签后面的第N个标签："//node[@id='3']/following-sibling::_[N]" ; 获取第三个node标签的上一个node标签："//node[@id='3']/preceding-sibling::node[1]" ; 获取第三个node标签的前面的第N个标签："//node[@id='3']/preceding-sibling::_[N]"
> ; 获取第三个node标签的父标签："//node[@id=='3']/.."
> ; ==============================================================================================================
> ; 首页Bottom栏xpath规则
> ; 强国通 | 百灵 | 学习 | 视听 | 我的
> rule_bottom_message = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_message"]/@bounds
> rule_bottom_ding = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_ding"]/@bounds
> rule_bottom_work = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_work"]/@bounds
> rule_bottom_contact = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_contact"]/@bounds
> rule_bottom_mine = //node[@resource-id="cn.xuexi.android:id/home_bottom_tab_button_mine"]/@bounds
> ; 我要答题xpath规则
> ; 我要答题入口，[我要答题]按钮
> rule_quiz_entry = //node[@content-desc="我要答题"]/@bounds
> ; 我要答题出口：[<]左上角后退按钮 我要答题父节点的第一个子节点,答题记录的前一个兄弟节点
> rule_quiz_exit = //node[@content-desc="答题记录"]/preceding-sibling::node[1]/@bounds
> ; 每日答题入口 [每日答题]按钮
> rule_daily_entry = //node[@content-desc="每日答题"]/@bounds
> ; 挑战答题入口　[挑战答题]按钮
> rule_challenge_entry = //node[@content-desc="挑战答题"]/@bounds
> ; ---------------------------------------------------------------------------------------------------------------
> ; 每日答题xpath规则
> ; 题型：填空题、单选题、多选题
> rule_type = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/preceding-sibling::node[1]/@content-desc
> ; 题干
> rule_content = //node[@Class="android.widget.ListView"]/../node[@index="2"]/@content-desc
> rule_blank_content = //node[@content-desc="1 /5" or @content-desc="2 /5" or @content-desc="3 /5" or @content-desc="4 /5" or @content-desc="5 /5"]/following-sibling::node[1]/node[@Class="android.view.View"]/@content-desc
> ; 选项坐标
> rule_options = //node[@Class="android.widget.ListView"]/node/@bounds
> ; 填空题输入框坐标
> rule_edits = //node[@Class="android.widget.EditText"]/following-sibling::node[1]/@bounds
> ; 分数
> rule_score = //node[@content-desc="积分： "]/following-sibling::node[1]/@content-desc
> rule_score_reached = //node[@content-desc="领取奖励已达今日上限"]/@content-desc
> ; 正确答案， node[答案解析]的下一个标签
> rule_desc = //node[@content-desc="答案解析"]/following-sibling::node[1]/@content-desc
> rule_note = //node[@content-desc="答案解析"]/following-sibling::node[2]/@content-desc
> 
> ; 按钮坐标 [<]左上角返回按钮、[确定、下一题、完成]右上角提交按钮、答题报告中返回按钮、答题报告中再来一组按钮
> rule_back = //node[@Class="android.widget.Button"]/../preceding-sibling::node[1]/@bounds
> rule_submit = //node[@Class="android.widget.Button"]/@bounds
> rule_return = //node[@content-desc="返回"]/@bounds
> rule_next = //node[@content-desc="再来一组"]/@bounds
> ; ==============================================================================================================
> ; 挑战答题xpath规则
> ; 题型：挑战题
> ; 题干
> rule_challenge_content = //node[@Class="android.widget.ListView"]/preceding-sibling::node[1]/@content-desc
> ; 选项内容
> rule_challenge_options_content = //node[@Class="android.widget.ListView"]/node//node[@index="1" and @Class="android.view.View"]/@content-desc
> ; 选项坐标
> rule_challenge_options_bounds = //node[@Class="android.widget.ListView"]/node/@bounds
> ; 复活按钮和再来一局按钮坐标
> rule_judge_bounds = //node[@content-desc="分享就能复活" or @content-desc="再来一局"]/@bounds
> rule_revive_bounds = //node[@content-desc="分享就能复活"]/@bounds
> rule_again_bounds = //node[@content-desc="再来一局"]/@bounds
> ; rule_close_bounds = //node[@content-desc="结束本局"]/bounds
> ; ==============================================================================================================
> 
> ; 视听学习xpath规则
> ; 百灵第一个视频
> rule_first_video = //node[@Class="android.widget.ListView"]/node[1]/@bounds
> 
> ; 阅读文章xpath规则
> rule_columns_content = //node[@Class="android.view.ViewGroup"]/node[@Class="android.widget.LinearLayout"]/node[@Class="android.widget.TextView"]/@text
> rule_columns_bounds = //node[@Class="android.view.ViewGroup"]/node[@Class="android.widget.LinearLayout"]/@bounds
> rule_fixed_top_bounds = ////node[@Class="android.widget.ListView"]/node[1]/@bounds
> rule_fixed_bottom_bounds = ////node[@Class="android.widget.ListView"]/node[last()]/@bounds
> rule_news_bounds = //node[@Class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@bounds
> rule_news_content = //node[@Class="android.widget.ListView"]//node[@resource-id="cn.xuexi.android:id/general_card_title_id"]/@text
> rule_news3pic_bounds = ////node[@Class="android.widget.ListView"]/node/node[@Class="android.widget.LinearLayout" and @index="0"]/node[@Class="android.widget.TextView"]/@bounds
> rule_news3pic_content = ////node[@Class="android.widget.ListView"]/node/node[@Class="android.widget.LinearLayout" and @index="0"]/node[@Class="android.widget.TextView"]/@text
> rule_star_bounds = //node[@text="欢迎发表你的观点"]/../node[3]/@bounds
> rule_share_bounds = //node[@text="欢迎发表你的观点"]/../node[4]/@bounds
> rule_comment_bounds = //node[@text="欢迎发表你的观点"]/@bounds
> rule_share2xuexi_bounds = //node[@text="分享到学习强国"]/@bounds
> rule_publish_bounds = //node[@text="发布"]/@bounds

你雷电什么版本?
