### ISSUE TITLE
每次到新闻学习就出错了

### ISSUE THREAD

**Issue by cedar-c** [kessil/AutoXue#66]
前天还好好的，昨天突然不能学习新闻了，订阅的新的可以了，今天又是出错，前面好好的，到了新闻学习就错了

Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "F:\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "F:\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "F:\AutoXue-master\xuexi\media\reader.py", line 200, in run
    self.ad.slide(complex(self.fixed.real, article[1].imag), self.fixed, duration=1000)
UnboundLocalError: local variable 'article' referenced before assignment

另外好像题库下载不了了，404

**Comment by kessil** [comment]
你先把enable_article_list = false改为true看看
注意观察是不是重复的两篇文章中间有一个上拉文章列表的过程？

**Comment by cedar-c** [comment]
> 你先把enable_article_list = false改为true看看
> 注意观察是不是重复的两篇文章中间有一个上拉文章列表的过程？

本来就是true。对，有上拉的过程。

**Comment by cedar-c** [comment]
另外关于连接雷电的问题，我已经被雷电整的心力交瘁了，但是真的雷电上面有好多东西，装两个有吃不住。 貌似是不能点到 我要答题 ，但是看了看xpath发现自己好像不会改。。。
Traceback (most recent call last):
File "F:\AutoXue-master\xuexi\common\adble.py", line 167, in tap
dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "D:\python\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "D:\python\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "F:\AutoXue-master\xuexi_main.py", line 41, in 
app.start(args.article, args.video, args.daily, args.challenge)
File "F:\AutoXue-master\xuexi_init.py", line 62, in start
self.quiz_run(day, chg)
File "F:\AutoXue-master\xuexi_init.py", line 57, in quiz_run
qApp.start(day, chg)
File "F:\AutoXue-master\xuexi\quiz_init.py", line 65, in start
self.ad.tap(pos)
File "F:\AutoXue-master\xuexi\common\adble.py", line 169, in tap
raise AttributeError(f'{x} 不是可点击的坐标')
AttributeError: [] 不是可点击的坐标
[uileidian.xml.txt](https://github.com/kessil/AutoXue/files/3516154/uileidian.xml.txt)

**Comment by kessil** [comment]
不是xpath的问题，根本就没有我要答题这个元素。看来uiautomator能获取完整布局的只能靠MuMu了
![批注 2019-08-19 214136](https://user-images.githubusercontent.com/11907802/63270152-27e4d000-c2ca-11e9-9b22-8ce6ec62d5eb.png)
我要答题等内容应该在我圈起来的位置，但是明显啥也没有

**Comment by kessil** [comment]
你在我的页面多uiautomator几次，看能不能获取到，然后再对比一下两种情况的xml文件有何区别，比如文件大小。页面停留在我的，运行下面的命令：
```
python -m xuexi.common.adble ./mine -v -u -s
```
然后就可以再根目录下找到两个文件mine.png和mine.xml，可以用vscode或在线http://tool.oschina.net/codeformat/xml格式化

**Comment by cedar-c** [comment]
> 不是xpath的问题，根本就没有我要答题这个元素。看来uiautomator能获取完整布局的只能靠MuMu了
> ![批注 2019-08-19 214136](https://user-images.githubusercontent.com/11907802/63270152-27e4d000-c2ca-11e9-9b22-8ce6ec62d5eb.png)
> 我要答题等内容应该在我圈起来的位置，但是明显啥也没有

看不了你的照片。。。

**Comment by cedar-c** [comment]
> 你在我的页面多uiautomator几次，看能不能获取到，然后再对比一下两种情况的xml文件有何区别，比如文件大小。页面停留在我的，运行下面的命令：
> 
> ```
> python -m xuexi.common.adble ./mine -v -u -s
> ```
> 
> 然后就可以再根目录下找到两个文件mine.png和mine.xml，可以用vscode或在线[http://tool.oschina.net/codeformat/xml格式化](http://tool.oschina.net/codeformat/xml%E6%A0%BC%E5%BC%8F%E5%8C%96)

根目录是说c盘吗？我咋没找到那两个文件

**Comment by kessil** [comment]
就是截图的vscode的minmap，就长这样，根目录就是xuexi的父目录，应该叫AutoXue-Master之类的吧

**Comment by cedar-c** [comment]
> 就是截图的vscode的minmap，就长这样，根目录就是xuexi的父目录，应该叫AutoXue-Master之类的吧

不知道为什么你发的截图看不了，也不能下载，我的根目录没有那两个文件啊
![捕获](https://user-images.githubusercontent.com/54062513/63309301-d7e92600-c328-11e9-8be2-c09a9cf1c602.JPG)

**Comment by kessil** [comment]
发现每次uiautomator之前等1、2秒就能获取到webview里面的元素，你试试雷电行不行。
找到./xuexi/common/adble.py文件第116行后面加一句sleep(3)，这样做的负面效果是所有uiautomator都会延时3秒，这样总时长会多出不少。。。先试试能得到元素不
就像这样
![批注 2019-08-20 234530](https://user-images.githubusercontent.com/11907802/63362566-a31ab480-c3a4-11e9-94a4-fca1bd6132c7.png)

**Comment by cedar-c** [comment]
> 发现每次uiautomator之前等1、2秒就能获取到webview里面的元素，你试试雷电行不行。
> 找到./xuexi/common/adble.py文件第116行后面加一句sleep(3)，这样做的负面效果是所有uiautomator都会延时3秒，这样总时长会多出不少。。。先试试能得到元素不
> 就像这样
> ![批注 2019-08-20 234530](https://user-images.githubusercontent.com/11907802/63362566-a31ab480-c3a4-11e9-94a4-fca1bd6132c7.png)

加了，还是会提醒一样的错误

**Comment by cedar-c** [comment]
> 你在我的页面多uiautomator几次，看能不能获取到，然后再对比一下两种情况的xml文件有何区别，比如文件大小。页面停留在我的，运行下面的命令：
> 
> ```
> python -m xuexi.common.adble ./mine -v -u -s
> ```
> 
> 然后就可以再根目录下找到两个文件mine.png和mine.xml，可以用vscode或在线[http://tool.oschina.net/codeformat/xml格式化](http://tool.oschina.net/codeformat/xml%E6%A0%BC%E5%BC%8F%E5%8C%96)

运行了命令，但是没有文件的出现
