### ISSUE TITLE
mac版考虑出个吗

### ISSUE THREAD

**Issue by idelin** [kessil/AutoXue#70]
rt

**Comment by kessil** [comment]
python本来就跨平台，只要mac能安装ADB和模拟器，做相应配置应该能用，不过我没有mac， 没法测试。

**Comment by idelin** [comment]
> python本来就跨平台，只要mac能安装ADB和模拟器，做相应配置应该能用，不过我没有mac， 没法测试。

完全明白，但是我在mac执行无法成功，修改了mac上mumu的端口也不行

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/delin/git/AutoXue/xuexi/__main__.py", line 40, in <module>
    app = App()
  File "/Users/delin/git/AutoXue/xuexi/__init__.py", line 35, in __init__
    cfg.getint(self.rules, 'port'))
  File "/Users/delin/git/AutoXue/xuexi/common/adble.py", line 29, in __init__
    self.device = self._getDevice()
  File "/Users/delin/git/AutoXue/xuexi/common/adble.py", line 102, in _getDevice
    res = subprocess.check_output(f'adb devices')
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'adb devices'
Exception ignored in: <bound method App.__del__ of <xuexi.App object at 0x1059cc7f0>>
Traceback (most recent call last):
  File "/Users/delin/git/AutoXue/xuexi/__init__.py", line 77, in __del__
    self.ad.close()
AttributeError: 'App' object has no attribute 'ad'
```

**Comment by kessil** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'adb devices'
也许你直接在terminal输入adb devices也没用，试一试

**Comment by tmp3000** [comment]
adb如何连接mumu模拟器   
【win版】
adb connect 127.0.0.1:7555
adb shell

【mac版】

adb kill-server && adb server && adb shell
