### ISSUE TITLE
大神，留言时出现错误

### ISSUE THREAD

**Issue by kickerp** [kessil/AutoXue#71]
留言一篇文章: 天蓝山绿水清，空气清新，人民身体更健康
Traceback (most recent call last):
  File "C:\Users\x-mini\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\x-mini\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "D:\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "D:\AutoXue-master\xuexi\media\reader.py", line 246, in run
    ssc -= self._star_share_comment(title)
  File "D:\AutoXue-master\xuexi\media\reader.py", line 163, in _star_share_comment
    offset = offset_dict[max(self.ad.wmsize)]
KeyError: 1600

**Comment by xp9388** [comment]
我也提示这个错误，更换分辨率测试，问题更多，现在又换回1600*900的分辨率

**Comment by xp9388** [comment]
找到原因了，需要设置默认输入法

**Comment by kickerp** [comment]
设置adb默认后还是一样..
