### ISSUE TITLE
MuMu各种分别率已尝试，提示不是可点坐标

### ISSUE THREAD

**Issue by coscyang** [kessil/AutoXue#77]
python == 3.7.2
ADB == 1.0.40
模拟器MuMu，自带分比率均测试过了，自定义1920*1080 320pi和1080*1920 320pi也设置过，均提示坐标不可点，具体提示如下：

F:\xuexiqiangguo\Scripts
λ python -m xuexi -a -c -d -v

        阅读文章视听学习每日答题挑战答题[√]

当前设备 127.0.0.1:7555
1102 KB/s (58420 bytes in 0.051s)
927 KB/s (27827 bytes in 0.029s)
Traceback (most recent call last):
  File "F:\xuexiqiangguo\Scripts\xuexi\common\adble.py", line 167, in tap
    dx, dy = int(x.real), int(x.imag)
AttributeError: 'list' object has no attribute 'real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\xuexiqiangguo\Scripts\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "F:\xuexiqiangguo\Scripts\xuexi\__init__.py", line 62, in start
    self._quiz_run(day, chg)
  File "F:\xuexiqiangguo\Scripts\xuexi\__init__.py", line 57, in _quiz_run
    qApp.start(day, chg)
  File "F:\xuexiqiangguo\Scripts\xuexi\quiz\__init__.py", line 65, in start
    self.ad.tap(pos)
  File "F:\xuexiqiangguo\Scripts\xuexi\common\adble.py", line 169, in tap
    raise AttributeError(f'{x} 不是可点击的坐标')
AttributeError: [] 不是可点击的坐标
断开模拟器127.0.0.1:62001 成功

**Comment by raidersj** [comment]
配置里设备名称改mumu就好了
