### ISSUE TITLE
合理化建议

### ISSUE THREAD

**Issue by wsl5778036** [kessil/AutoXue#91]
现在是先做题后检测，例如我每日答题都做完了。点击开始后他还是要先答一次题再判断是否继续答题。挑战答题不管是否答对5题都要连续挑战到设定次数为止。视频学习也是不管有没有学习都是从头开始学。建议能够先检测分数后答题。还有你的参数设置及运行监控是否写成exe方便设置呢？

**Comment by wsl5778036** [comment]
经常这样

**Comment by wsl5778036** [comment]
自动提交答案 A

[挑战题] “落其实者思其（ ），饮其流者怀其源”，请补足诗句。...
A. 叶
B. 根
C. 源
D. 树
自动提交答案 D

[挑战题] 中央国家机关、省级机关及其授权的机关、单位可以确定        的国家秘密。
（出题单位：...
A. 绝密级
B. 机密级
C. 秘密级
D. 以上全部
自动提交答案 D

[挑战题] “苟利国家生死以，岂因祸福避趋之”的作者是        。（出题单位：南开大
学文学院）...
A. 龚自珍
B. 谭嗣同
C. 林则徐
D. 梁启超
自动提交答案 C

[挑战题] “苏南四小龙”是分别        。（出题单位：常熟理工学院 推荐单位：江苏学
习平台）...
A. 常熟 太仓 张家港 昆山
B. 昆山 江阴 张家港 常熟
C. 张家港 太仓 昆山 江阴
自动提交答案 B

[挑战题] 北宋        发明的活字印刷术比欧洲早400年。（出题单位：山东科技报社 推
荐单位：...
A. 蔡伦
B. 毕昇
C. 沈括
D. 王祯
自动提交答案 B

[挑战题] 当前，我们正处于信息化建设第        次浪潮的起始期。（出题单位：山东科
技报社 推荐...
A. 一
B. 二
C. 三
D. 四
自动提交答案 C

[挑战题] 当遭遇大风时，应避免走高楼之间的狭长通道，因为在狭窄的通道中，会形成“
狭管效应”，风力  ...
A. 增大
B. 不变
C. 减小
自动提交答案 A

[挑战题] 1963年出土于陕西省宝鸡市宝鸡县贾村镇（今宝鸡市陈仓区）的        ，造型
庄严厚重...
A. 何尊
B. 四羊方尊
C. 妇好鸮尊
D. 亚酗（xù）方尊
自动提交答案 A

[挑战题] 根据《中华人民共和国国家安全法》规定，        依照宪法规定，决定战争状
态的宣布，决...
A. 全国人民代表大会
B. 全国人民代表大会常务委员会
C. 中华人民共和国主席
D. 国务院
自动提交答案 B

[挑战题] 古代科举考试中殿试的第三名叫什么？        （ 出题单位：山东科技报社 推
荐单位：山...
A. 状元
B. 榜眼
C. 探花
D. 进士
自动提交答案 C

[挑战题] “不惑之年”指的是        。（出题单位：中共海安市委宣传部 推荐单位：江
苏学习平台...
A. 二十岁
B. 三十岁
C. 四十岁
D. 五十岁
自动提交答案 C

[挑战题] 2016年11月18日下午，神舟十一号载人飞船平安着陆，创下中国航天员太空驻留
时间的新纪录...
A. ①②④③
B. ②③④①
C. ②④①③
D. ②①④③
自动提交答案 C

[挑战题] “山郡逢春复乍晴，陂塘分出几泉清？郭边万户皆临水，雪后千峰半入城。”清
代诗人王士祯这首诗写...
A. 成都
B. 杭州
C. 泉州
D. 济南
自动提交答案 D

[挑战题] 治贫先治愚，扶贫先扶智。（ ）是阻断贫困代际传递的治本之策。...
A. 教育
B. 就业
C. 搬迁
自动提交答案 A

[挑战题] 四川省规模最大的民办博物馆是        。（出题单位：四川省文化和旅游厅 推
荐单位：四...
A. 建川博物馆
B. 华希昆虫博物馆
C. 成都川菜博物馆
D. 许燎原博物馆
自动提交答案 A

[挑战题] 2016年4月19日，习近平总书记在网络安全和信息化工作座谈会上指出，网络空间
的竞争，归根...
A. 经济竞争
B. 人才竞争
C. 技术竞争
D. 国力竞争
自动提交答案 B

[挑战题] 利用均匀水流导致的水位变化来显示时间，是        的基本原理。...
A. 漏刻计时
B. 钟表计时
C. 日晷计时
自动提交答案 A

[挑战题] 水上遇险求救电话号是        。（出题单位：河北海事局 推荐单位：河北学习
平台）...
A. 12395
B. 12935
C. 13925
D. 110
自动提交答案 A

[挑战题]         是一级政府应承担的运用财政资金提供基本公共服务的任务和职责。（
出题单位：北...
A. 财政事权
B. 事权
C. 财权
D. 财力
自动提交答案 A

[挑战题] “小李杜”指        。（出题单位：江苏省扬州市江都区委宣传部 推荐单位：
江苏学习平...
A. 李白杜甫
B. 李白杜牧
C. 李商隐杜牧
D. 李商隐杜甫
自动提交答案 C

[挑战题] 坚持和发展中国特色社会主义是一篇大文章，为它确定基本思路和基本原则的是
       ...
A. 马克思
B. 毛泽东
C. 邓小平
自动提交答案 C

[挑战题] 决定成立国家安全委员会的是（ ）。...
A. 党的十八届三中全会
B. 党的十八届四中全会
C. 党的十八届五中全会
自动提交答案 A

[挑战题] 为了兼顾节能与舒适，盛夏时室内空调设定温度不应低于        度。 （出题单
位：科技部...
A. 20℃
B. 24℃
C. 26℃
D. 28℃
自动提交答案 C

[挑战题] 在道路上醉酒驾驶机动车的，        。（出题单位：公安部交通管理局）...
A. 处管制，并处罚金
B. 处拘役，并处罚金
C. 处3年以下有期徒刑
D. 处3年以上有期徒刑
自动提交答案 B

[挑战题] 第二届全国青年运动会首次设立了        项目。
A. 公路自行车: 0
B. 手球: 0
C. 冰雪: 6
试探性提交答案 C 延时10秒中...
数据库添加记录成功！

[挑战题] 唐代岑参《白雪歌送武判官归京》中的“瀚海阑干百丈冰”中的“瀚海”是指
     。...
A. 大海
B. 沙漠
C. 星河
D. 湖泊
自动提交答案 B

[挑战题] “浩荡离愁白日斜，吟鞭东指即天涯。落红不是无情物，化作春泥更护花”的作
者与下列哪位不属于同...
A. 林则徐
B. 蒋春霖
C. 文天祥
D. 黄燮清
自动提交答案 C

[挑战题] 重庆解放的具体时间是        。（出题单位：重庆市委直属机关工委 推荐单位
：重庆学习...
A. 1949年10月1日
B. 1949年11月1日
C. 1949年11月30日
D. 1949年12月11日
自动提交答案 C

[挑战题] 奥运历史上第一个既举办过夏季奥运会，又举办冬季奥运会的城市是        。.
..
A. 慕尼黑
B. 北京
C. 巴黎
D. 东京
自动提交答案 B

[挑战题] 《四元玉鉴》是中国数学著作中最重要的，同时也是中世纪最杰出的数学著作之
一。它是世界数学宝库...
A. 元
B. 明
C. 清
D. 宋
自动提交答案 A

[挑战题] 东周时代秦国建立后实行的三公九卿制中的“三公”不包括        。（出题单
位：陕西历史...
A. 廷尉
B. 御史大夫
C. 太尉
D. 丞相
自动提交答案 A
已达成目标题数，延时30秒等待死亡中...
已达成目标题数 35 题，退出挑战
完成挑战答题，请稍候片刻...
答题耗时 543.81 秒
视听学习中...
视听学习第 29 则，耗时 56.31 秒
视听学习第 28 则，耗时 56.24 秒
视听学习第 27 则，耗时 56.27 秒
视听学习第 26 则，耗时 56.20 秒
视听学习第 25 则，耗时 56.27 秒
视听学习第 24 则，耗时 56.14 秒
视听学习第 23 则，耗时 56.35 秒
视听学习第 22 则，耗时 56.13 秒
视听学习第 21 则，耗时 56.16 秒
视听学习第 20 则，耗时 56.18 秒
视听学习第 19 则，耗时 56.17 秒
视听学习第 18 则，耗时 56.20 秒
视听学习第 17 则，耗时 56.22 秒
视听学习第 16 则，耗时 56.19 秒
视听学习第 15 则，耗时 56.18 秒
视听学习第 14 则，耗时 56.22 秒
视听学习第 13 则，耗时 56.24 秒
视听学习第 12 则，耗时 56.17 秒
视听学习第 11 则，耗时 56.27 秒
视听学习第 10 则，耗时 56.15 秒
视听学习第 9 则，耗时 56.20 秒
视听学习第 8 则，耗时 56.24 秒
视听学习第 7 则，耗时 56.23 秒
视听学习第 6 则，耗时 56.18 秒
视听学习第 5 则，耗时 56.19 秒
视听学习第 4 则，耗时 56.26 秒
视听学习第 3 则，耗时 56.22 秒
视听学习第 2 则，耗时 56.26 秒
视听学习第 1 则，耗时 56.28 秒
视听学习第 0 则，耗时 56.30 秒
视听学习完成，返回首页
视听学习耗时 1711.46 秒
新闻学习中...
[24] 新华快评：决不允许暴力升级将香港引向危险境地...
新闻：第 24 则已阅，耗时 46.46 秒
[23] 超高时空分辨率汤姆逊散射诊断系统问世...
分享一篇文章!
留言一篇文章: 不忘初心方得始终，牢记使命报效祖国
收藏一篇文章!
新闻：第 23 则已阅，耗时 60.38 秒
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\autoxue\AutoXue-master\xuexi\__main__.py", line 41, in <module>
    app.start(args.article, args.video, args.daily, args.challenge)
  File "D:\autoxue\AutoXue-master\xuexi\__init__.py", line 72, in start
    self._art_run()
  File "D:\autoxue\AutoXue-master\xuexi\__init__.py", line 44, in _art_run
    rd.run(count, delay, ssc)
  File "D:\autoxue\AutoXue-master\xuexi\media\reader.py", line 232, in run
    if pos_bottom.imag > self.fixed_bottom.imag:
AttributeError: 'list' object has no attribute 'imag'
断开模拟器127.0.0.1:7555 成功
请按任意键继续. . .
